// Generated by audio-source/render.py; local assets are embedded by the production bundler.
import a0_ogg from './ambient_castle.ogg';
import a0_mp3 from './ambient_castle.mp3';
import a1_ogg from './ambient_forest.ogg';
import a1_mp3 from './ambient_forest.mp3';
import a2_ogg from './ambient_meadow.ogg';
import a2_mp3 from './ambient_meadow.mp3';
import a3_ogg from './ambient_night.ogg';
import a3_mp3 from './ambient_night.mp3';
import a4_ogg from './ambient_wind.ogg';
import a4_mp3 from './ambient_wind.mp3';
import a5_ogg from './armor_1.ogg';
import a5_mp3 from './armor_1.mp3';
import a6_ogg from './armor_2.ogg';
import a6_mp3 from './armor_2.mp3';
import a7_ogg from './armor_3.ogg';
import a7_mp3 from './armor_3.mp3';
import a8_ogg from './arrow_flesh_1.ogg';
import a8_mp3 from './arrow_flesh_1.mp3';
import a9_ogg from './arrow_flesh_2.ogg';
import a9_mp3 from './arrow_flesh_2.mp3';
import a10_ogg from './arrow_impact_1.ogg';
import a10_mp3 from './arrow_impact_1.mp3';
import a11_ogg from './arrow_impact_2.ogg';
import a11_mp3 from './arrow_impact_2.mp3';
import a12_ogg from './arrow_impact_3.ogg';
import a12_mp3 from './arrow_impact_3.mp3';
import a13_ogg from './arrow_pass_1.ogg';
import a13_mp3 from './arrow_pass_1.mp3';
import a14_ogg from './arrow_pass_2.ogg';
import a14_mp3 from './arrow_pass_2.mp3';
import a15_ogg from './arrow_pass_3.ogg';
import a15_mp3 from './arrow_pass_3.mp3';
import a16_ogg from './arrow_stone_1.ogg';
import a16_mp3 from './arrow_stone_1.mp3';
import a17_ogg from './arrow_stone_2.ogg';
import a17_mp3 from './arrow_stone_2.mp3';
import a18_ogg from './arrow_wood_1.ogg';
import a18_mp3 from './arrow_wood_1.mp3';
import a19_ogg from './arrow_wood_2.ogg';
import a19_mp3 from './arrow_wood_2.mp3';
import a20_ogg from './bird_1.ogg';
import a20_mp3 from './bird_1.mp3';
import a21_ogg from './bird_2.ogg';
import a21_mp3 from './bird_2.mp3';
import a22_ogg from './bird_3.ogg';
import a22_mp3 from './bird_3.mp3';
import a23_ogg from './bird_4.ogg';
import a23_mp3 from './bird_4.mp3';
import a24_ogg from './bird_night_1.ogg';
import a24_mp3 from './bird_night_1.mp3';
import a25_ogg from './bird_night_2.ogg';
import a25_mp3 from './bird_night_2.mp3';
import a26_ogg from './block_1.ogg';
import a26_mp3 from './block_1.mp3';
import a27_ogg from './block_2.ogg';
import a27_mp3 from './block_2.mp3';
import a28_ogg from './block_3.ogg';
import a28_mp3 from './block_3.mp3';
import a29_ogg from './bow_draw_1.ogg';
import a29_mp3 from './bow_draw_1.mp3';
import a30_ogg from './bow_draw_2.ogg';
import a30_mp3 from './bow_draw_2.mp3';
import a31_ogg from './bow_release_1.ogg';
import a31_mp3 from './bow_release_1.mp3';
import a32_ogg from './bow_release_2.ogg';
import a32_mp3 from './bow_release_2.mp3';
import a33_ogg from './bow_release_3.ogg';
import a33_mp3 from './bow_release_3.mp3';
import a34_ogg from './cloth_1.ogg';
import a34_mp3 from './cloth_1.mp3';
import a35_ogg from './cloth_2.ogg';
import a35_mp3 from './cloth_2.mp3';
import a36_ogg from './cloth_3.ogg';
import a36_mp3 from './cloth_3.mp3';
import a37_ogg from './death_1.ogg';
import a37_mp3 from './death_1.mp3';
import a38_ogg from './door_1.ogg';
import a38_mp3 from './door_1.mp3';
import a39_ogg from './door_2.ogg';
import a39_mp3 from './door_2.mp3';
import a40_ogg from './enemy_death_1.ogg';
import a40_mp3 from './enemy_death_1.mp3';
import a41_ogg from './enemy_death_2.ogg';
import a41_mp3 from './enemy_death_2.mp3';
import a42_ogg from './enemy_death_3.ogg';
import a42_mp3 from './enemy_death_3.mp3';
import a43_ogg from './fire_charge_1.ogg';
import a43_mp3 from './fire_charge_1.mp3';
import a44_ogg from './fire_charge_2.ogg';
import a44_mp3 from './fire_charge_2.mp3';
import a45_ogg from './fire_impact_1.ogg';
import a45_mp3 from './fire_impact_1.mp3';
import a46_ogg from './fire_impact_2.ogg';
import a46_mp3 from './fire_impact_2.mp3';
import a47_ogg from './fire_impact_3.ogg';
import a47_mp3 from './fire_impact_3.mp3';
import a48_ogg from './fire_linger_1.ogg';
import a48_mp3 from './fire_linger_1.mp3';
import a49_ogg from './fire_release_1.ogg';
import a49_mp3 from './fire_release_1.mp3';
import a50_ogg from './fire_release_2.ogg';
import a50_mp3 from './fire_release_2.mp3';
import a51_ogg from './fire_travel_1.ogg';
import a51_mp3 from './fire_travel_1.mp3';
import a52_ogg from './fire_travel_2.ogg';
import a52_mp3 from './fire_travel_2.mp3';
import a53_ogg from './flesh_1.ogg';
import a53_mp3 from './flesh_1.mp3';
import a54_ogg from './flesh_2.ogg';
import a54_mp3 from './flesh_2.mp3';
import a55_ogg from './flesh_3.ogg';
import a55_mp3 from './flesh_3.mp3';
import a56_ogg from './latch_1.ogg';
import a56_mp3 from './latch_1.mp3';
import a57_ogg from './latch_2.ogg';
import a57_mp3 from './latch_2.mp3';
import a58_ogg from './leaves_1.ogg';
import a58_mp3 from './leaves_1.mp3';
import a59_ogg from './leaves_2.ogg';
import a59_mp3 from './leaves_2.mp3';
import a60_ogg from './leaves_3.ogg';
import a60_mp3 from './leaves_3.mp3';
import a61_ogg from './miss_1.ogg';
import a61_mp3 from './miss_1.mp3';
import a62_ogg from './miss_2.ogg';
import a62_mp3 from './miss_2.mp3';
import a63_ogg from './parry_1.ogg';
import a63_mp3 from './parry_1.mp3';
import a64_ogg from './parry_2.ogg';
import a64_mp3 from './parry_2.mp3';
import a65_ogg from './parry_3.ogg';
import a65_mp3 from './parry_3.mp3';
import a66_ogg from './respawn_1.ogg';
import a66_mp3 from './respawn_1.mp3';
import a67_ogg from './rest_1.ogg';
import a67_mp3 from './rest_1.mp3';
import a68_ogg from './shield_1.ogg';
import a68_mp3 from './shield_1.mp3';
import a69_ogg from './shield_2.ogg';
import a69_mp3 from './shield_2.mp3';
import a70_ogg from './shield_3.ogg';
import a70_mp3 from './shield_3.mp3';
import a71_ogg from './shield_break_1.ogg';
import a71_mp3 from './shield_break_1.mp3';
import a72_ogg from './step_dirt_1.ogg';
import a72_mp3 from './step_dirt_1.mp3';
import a73_ogg from './step_dirt_2.ogg';
import a73_mp3 from './step_dirt_2.mp3';
import a74_ogg from './step_dirt_3.ogg';
import a74_mp3 from './step_dirt_3.mp3';
import a75_ogg from './step_dirt_4.ogg';
import a75_mp3 from './step_dirt_4.mp3';
import a76_ogg from './step_grass_1.ogg';
import a76_mp3 from './step_grass_1.mp3';
import a77_ogg from './step_grass_2.ogg';
import a77_mp3 from './step_grass_2.mp3';
import a78_ogg from './step_grass_3.ogg';
import a78_mp3 from './step_grass_3.mp3';
import a79_ogg from './step_grass_4.ogg';
import a79_mp3 from './step_grass_4.mp3';
import a80_ogg from './step_stone_1.ogg';
import a80_mp3 from './step_stone_1.mp3';
import a81_ogg from './step_stone_2.ogg';
import a81_mp3 from './step_stone_2.mp3';
import a82_ogg from './step_stone_3.ogg';
import a82_mp3 from './step_stone_3.mp3';
import a83_ogg from './step_stone_4.ogg';
import a83_mp3 from './step_stone_4.mp3';
import a84_ogg from './step_wood_1.ogg';
import a84_mp3 from './step_wood_1.mp3';
import a85_ogg from './step_wood_2.ogg';
import a85_mp3 from './step_wood_2.mp3';
import a86_ogg from './step_wood_3.ogg';
import a86_mp3 from './step_wood_3.mp3';
import a87_ogg from './step_wood_4.ogg';
import a87_mp3 from './step_wood_4.mp3';
import a88_ogg from './ui_1.ogg';
import a88_mp3 from './ui_1.mp3';
import a89_ogg from './ui_2.ogg';
import a89_mp3 from './ui_2.mp3';
import a90_ogg from './ui_cancel_1.ogg';
import a90_mp3 from './ui_cancel_1.mp3';
import a91_ogg from './ui_confirm_1.ogg';
import a91_mp3 from './ui_confirm_1.mp3';
import a92_ogg from './whoosh_heavy_1.ogg';
import a92_mp3 from './whoosh_heavy_1.mp3';
import a93_ogg from './whoosh_heavy_2.ogg';
import a93_mp3 from './whoosh_heavy_2.mp3';
import a94_ogg from './whoosh_heavy_3.ogg';
import a94_mp3 from './whoosh_heavy_3.mp3';
import a95_ogg from './whoosh_light_1.ogg';
import a95_mp3 from './whoosh_light_1.mp3';
import a96_ogg from './whoosh_light_2.ogg';
import a96_mp3 from './whoosh_light_2.mp3';
import a97_ogg from './whoosh_light_3.ogg';
import a97_mp3 from './whoosh_light_3.mp3';
import a98_ogg from './room_ir.ogg';
import a98_mp3 from './room_ir.mp3';
import a99_ogg from './music_duel.ogg';
import a99_mp3 from './music_duel.mp3';
import a100_ogg from './music_forest.ogg';
import a100_mp3 from './music_forest.mp3';
import a101_ogg from './music_meadow.ogg';
import a101_mp3 from './music_meadow.mp3';
import a102_ogg from './music_rescue.ogg';
import a102_mp3 from './music_rescue.mp3';
import a103_ogg from './music_royal.ogg';
import a103_mp3 from './music_royal.mp3';
import a104_ogg from './music_title.ogg';
import a104_mp3 from './music_title.mp3';
import a105_ogg from './silence.ogg';
import a105_mp3 from './silence.mp3';

export type AudioAsset = { id: string; group: string; kind: 'music' | 'ambience' | 'effect' | 'ir' | 'silence'; duration: number; channels: number; sampleRate: number; pcmBytes: number; loop: boolean; peak: number; rms: number; ogg: string; mp3: string };
export const AUDIO_ASSETS: readonly AudioAsset[] = [
  {...{"id":"ambient_castle","group":"castle","kind":"ambience","duration":24.0,"channels":2,"sampleRate":24000,"pcmBytes":4608000,"loop":true,"peak":0.3560149,"rms":0.064}, ogg: a0_ogg, mp3: a0_mp3},
  {...{"id":"ambient_forest","group":"forest","kind":"ambience","duration":24.0,"channels":2,"sampleRate":24000,"pcmBytes":4608000,"loop":true,"peak":0.3453191,"rms":0.064}, ogg: a1_ogg, mp3: a1_mp3},
  {...{"id":"ambient_meadow","group":"meadow","kind":"ambience","duration":24.0,"channels":2,"sampleRate":24000,"pcmBytes":4608000,"loop":true,"peak":0.36,"rms":0.0613609}, ogg: a2_ogg, mp3: a2_mp3},
  {...{"id":"ambient_night","group":"night","kind":"ambience","duration":24.0,"channels":2,"sampleRate":24000,"pcmBytes":4608000,"loop":true,"peak":0.36,"rms":0.0559394}, ogg: a3_ogg, mp3: a3_mp3},
  {...{"id":"ambient_wind","group":"wind","kind":"ambience","duration":24.0,"channels":2,"sampleRate":24000,"pcmBytes":4608000,"loop":true,"peak":0.36,"rms":0.0574716}, ogg: a4_ogg, mp3: a4_mp3},
  {...{"id":"armor_1","group":"armor","kind":"effect","duration":0.53,"channels":1,"sampleRate":24000,"pcmBytes":50880,"loop":false,"peak":0.56,"rms":0.0356065}, ogg: a5_ogg, mp3: a5_mp3},
  {...{"id":"armor_2","group":"armor","kind":"effect","duration":0.53,"channels":1,"sampleRate":24000,"pcmBytes":50880,"loop":false,"peak":0.56,"rms":0.0272996}, ogg: a6_ogg, mp3: a6_mp3},
  {...{"id":"armor_3","group":"armor","kind":"effect","duration":0.53,"channels":1,"sampleRate":24000,"pcmBytes":50880,"loop":false,"peak":0.56,"rms":0.0388484}, ogg: a7_ogg, mp3: a7_mp3},
  {...{"id":"arrow_flesh_1","group":"arrow_flesh","kind":"effect","duration":0.39,"channels":1,"sampleRate":24000,"pcmBytes":37440,"loop":false,"peak":0.56,"rms":0.0670222}, ogg: a8_ogg, mp3: a8_mp3},
  {...{"id":"arrow_flesh_2","group":"arrow_flesh","kind":"effect","duration":0.39,"channels":1,"sampleRate":24000,"pcmBytes":37440,"loop":false,"peak":0.56,"rms":0.06699}, ogg: a9_ogg, mp3: a9_mp3},
  {...{"id":"arrow_impact_1","group":"arrow_impact","kind":"effect","duration":0.569958,"channels":1,"sampleRate":24000,"pcmBytes":54716,"loop":false,"peak":0.56,"rms":0.0375171}, ogg: a10_ogg, mp3: a10_mp3},
  {...{"id":"arrow_impact_2","group":"arrow_impact","kind":"effect","duration":0.569958,"channels":1,"sampleRate":24000,"pcmBytes":54716,"loop":false,"peak":0.56,"rms":0.044109}, ogg: a11_ogg, mp3: a11_mp3},
  {...{"id":"arrow_impact_3","group":"arrow_impact","kind":"effect","duration":0.569958,"channels":1,"sampleRate":24000,"pcmBytes":54716,"loop":false,"peak":0.56,"rms":0.0439572}, ogg: a12_ogg, mp3: a12_mp3},
  {...{"id":"arrow_pass_1","group":"arrow_pass","kind":"effect","duration":0.43,"channels":1,"sampleRate":24000,"pcmBytes":41280,"loop":false,"peak":0.56,"rms":0.0806134}, ogg: a13_ogg, mp3: a13_mp3},
  {...{"id":"arrow_pass_2","group":"arrow_pass","kind":"effect","duration":0.43,"channels":1,"sampleRate":24000,"pcmBytes":41280,"loop":false,"peak":0.56,"rms":0.077131}, ogg: a14_ogg, mp3: a14_mp3},
  {...{"id":"arrow_pass_3","group":"arrow_pass","kind":"effect","duration":0.43,"channels":1,"sampleRate":24000,"pcmBytes":41280,"loop":false,"peak":0.56,"rms":0.0805985}, ogg: a15_ogg, mp3: a15_mp3},
  {...{"id":"arrow_stone_1","group":"arrow_stone","kind":"effect","duration":0.65,"channels":1,"sampleRate":24000,"pcmBytes":62400,"loop":false,"peak":0.56,"rms":0.030352}, ogg: a16_ogg, mp3: a16_mp3},
  {...{"id":"arrow_stone_2","group":"arrow_stone","kind":"effect","duration":0.65,"channels":1,"sampleRate":24000,"pcmBytes":62400,"loop":false,"peak":0.56,"rms":0.0309088}, ogg: a17_ogg, mp3: a17_mp3},
  {...{"id":"arrow_wood_1","group":"arrow_wood","kind":"effect","duration":0.55,"channels":1,"sampleRate":24000,"pcmBytes":52800,"loop":false,"peak":0.56,"rms":0.0456316}, ogg: a18_ogg, mp3: a18_mp3},
  {...{"id":"arrow_wood_2","group":"arrow_wood","kind":"effect","duration":0.55,"channels":1,"sampleRate":24000,"pcmBytes":52800,"loop":false,"peak":0.56,"rms":0.0387924}, ogg: a19_ogg, mp3: a19_mp3},
  {...{"id":"bird_1","group":"bird","kind":"effect","duration":1.1,"channels":1,"sampleRate":24000,"pcmBytes":105600,"loop":false,"peak":0.4212384,"rms":0.115}, ogg: a20_ogg, mp3: a20_mp3},
  {...{"id":"bird_2","group":"bird","kind":"effect","duration":1.21,"channels":1,"sampleRate":24000,"pcmBytes":116160,"loop":false,"peak":0.4417294,"rms":0.115}, ogg: a21_ogg, mp3: a21_mp3},
  {...{"id":"bird_3","group":"bird","kind":"effect","duration":1.32,"channels":1,"sampleRate":24000,"pcmBytes":126720,"loop":false,"peak":0.4614738,"rms":0.115}, ogg: a22_ogg, mp3: a22_mp3},
  {...{"id":"bird_4","group":"bird","kind":"effect","duration":1.43,"channels":1,"sampleRate":24000,"pcmBytes":137280,"loop":false,"peak":0.4801265,"rms":0.115}, ogg: a23_ogg, mp3: a23_mp3},
  {...{"id":"bird_night_1","group":"bird_night","kind":"effect","duration":1.1,"channels":1,"sampleRate":24000,"pcmBytes":105600,"loop":false,"peak":0.3300186,"rms":0.115}, ogg: a24_ogg, mp3: a24_mp3},
  {...{"id":"bird_night_2","group":"bird_night","kind":"effect","duration":1.21,"channels":1,"sampleRate":24000,"pcmBytes":116160,"loop":false,"peak":0.3459536,"rms":0.115}, ogg: a25_ogg, mp3: a25_mp3},
  {...{"id":"block_1","group":"block","kind":"effect","duration":0.569958,"channels":1,"sampleRate":24000,"pcmBytes":54716,"loop":false,"peak":0.56,"rms":0.0344597}, ogg: a26_ogg, mp3: a26_mp3},
  {...{"id":"block_2","group":"block","kind":"effect","duration":0.569958,"channels":1,"sampleRate":24000,"pcmBytes":54716,"loop":false,"peak":0.56,"rms":0.0347596}, ogg: a27_ogg, mp3: a27_mp3},
  {...{"id":"block_3","group":"block","kind":"effect","duration":0.569958,"channels":1,"sampleRate":24000,"pcmBytes":54716,"loop":false,"peak":0.56,"rms":0.039237}, ogg: a28_ogg, mp3: a28_mp3},
  {...{"id":"bow_draw_1","group":"bow_draw","kind":"effect","duration":0.8,"channels":1,"sampleRate":24000,"pcmBytes":76800,"loop":false,"peak":0.56,"rms":0.0957536}, ogg: a29_ogg, mp3: a29_mp3},
  {...{"id":"bow_draw_2","group":"bow_draw","kind":"effect","duration":0.8,"channels":1,"sampleRate":24000,"pcmBytes":76800,"loop":false,"peak":0.56,"rms":0.0959717}, ogg: a30_ogg, mp3: a30_mp3},
  {...{"id":"bow_release_1","group":"bow_release","kind":"effect","duration":0.44,"channels":1,"sampleRate":24000,"pcmBytes":42240,"loop":false,"peak":0.56,"rms":0.0580725}, ogg: a31_ogg, mp3: a31_mp3},
  {...{"id":"bow_release_2","group":"bow_release","kind":"effect","duration":0.44,"channels":1,"sampleRate":24000,"pcmBytes":42240,"loop":false,"peak":0.56,"rms":0.0568681}, ogg: a32_ogg, mp3: a32_mp3},
  {...{"id":"bow_release_3","group":"bow_release","kind":"effect","duration":0.44,"channels":1,"sampleRate":24000,"pcmBytes":42240,"loop":false,"peak":0.56,"rms":0.0593174}, ogg: a33_ogg, mp3: a33_mp3},
  {...{"id":"cloth_1","group":"cloth","kind":"effect","duration":0.47,"channels":1,"sampleRate":24000,"pcmBytes":45120,"loop":false,"peak":0.56,"rms":0.0689795}, ogg: a34_ogg, mp3: a34_mp3},
  {...{"id":"cloth_2","group":"cloth","kind":"effect","duration":0.47,"channels":1,"sampleRate":24000,"pcmBytes":45120,"loop":false,"peak":0.56,"rms":0.0715176}, ogg: a35_ogg, mp3: a35_mp3},
  {...{"id":"cloth_3","group":"cloth","kind":"effect","duration":0.47,"channels":1,"sampleRate":24000,"pcmBytes":45120,"loop":false,"peak":0.56,"rms":0.0626716}, ogg: a36_ogg, mp3: a36_mp3},
  {...{"id":"death_1","group":"death","kind":"effect","duration":3.1,"channels":1,"sampleRate":24000,"pcmBytes":297600,"loop":false,"peak":0.4387278,"rms":0.115}, ogg: a37_ogg, mp3: a37_mp3},
  {...{"id":"door_1","group":"door","kind":"effect","duration":1.45,"channels":1,"sampleRate":24000,"pcmBytes":139200,"loop":false,"peak":0.56,"rms":0.0725961}, ogg: a38_ogg, mp3: a38_mp3},
  {...{"id":"door_2","group":"door","kind":"effect","duration":1.45,"channels":1,"sampleRate":24000,"pcmBytes":139200,"loop":false,"peak":0.56,"rms":0.0622811}, ogg: a39_ogg, mp3: a39_mp3},
  {...{"id":"enemy_death_1","group":"enemy_death","kind":"effect","duration":1.08,"channels":1,"sampleRate":24000,"pcmBytes":103680,"loop":false,"peak":0.56,"rms":0.1040579}, ogg: a40_ogg, mp3: a40_mp3},
  {...{"id":"enemy_death_2","group":"enemy_death","kind":"effect","duration":1.08,"channels":1,"sampleRate":24000,"pcmBytes":103680,"loop":false,"peak":0.56,"rms":0.0982702}, ogg: a41_ogg, mp3: a41_mp3},
  {...{"id":"enemy_death_3","group":"enemy_death","kind":"effect","duration":1.08,"channels":1,"sampleRate":24000,"pcmBytes":103680,"loop":false,"peak":0.56,"rms":0.0973338}, ogg: a42_ogg, mp3: a42_mp3},
  {...{"id":"fire_charge_1","group":"fire_charge","kind":"effect","duration":1.18,"channels":1,"sampleRate":24000,"pcmBytes":113280,"loop":false,"peak":0.56,"rms":0.0990848}, ogg: a43_ogg, mp3: a43_mp3},
  {...{"id":"fire_charge_2","group":"fire_charge","kind":"effect","duration":1.18,"channels":1,"sampleRate":24000,"pcmBytes":113280,"loop":false,"peak":0.56,"rms":0.0953578}, ogg: a44_ogg, mp3: a44_mp3},
  {...{"id":"fire_impact_1","group":"fire_impact","kind":"effect","duration":1.05,"channels":1,"sampleRate":24000,"pcmBytes":100800,"loop":false,"peak":0.56,"rms":0.0442494}, ogg: a45_ogg, mp3: a45_mp3},
  {...{"id":"fire_impact_2","group":"fire_impact","kind":"effect","duration":1.05,"channels":1,"sampleRate":24000,"pcmBytes":100800,"loop":false,"peak":0.56,"rms":0.0601236}, ogg: a46_ogg, mp3: a46_mp3},
  {...{"id":"fire_impact_3","group":"fire_impact","kind":"effect","duration":1.05,"channels":1,"sampleRate":24000,"pcmBytes":100800,"loop":false,"peak":0.56,"rms":0.0576665}, ogg: a47_ogg, mp3: a47_mp3},
  {...{"id":"fire_linger_1","group":"fire_linger","kind":"effect","duration":2.8,"channels":1,"sampleRate":24000,"pcmBytes":268800,"loop":false,"peak":0.5599999,"rms":0.0888212}, ogg: a48_ogg, mp3: a48_mp3},
  {...{"id":"fire_release_1","group":"fire_release","kind":"effect","duration":0.66,"channels":1,"sampleRate":24000,"pcmBytes":63360,"loop":false,"peak":0.56,"rms":0.0598622}, ogg: a49_ogg, mp3: a49_mp3},
  {...{"id":"fire_release_2","group":"fire_release","kind":"effect","duration":0.66,"channels":1,"sampleRate":24000,"pcmBytes":63360,"loop":false,"peak":0.56,"rms":0.0704571}, ogg: a50_ogg, mp3: a50_mp3},
  {...{"id":"fire_travel_1","group":"fire_travel","kind":"effect","duration":1.25,"channels":1,"sampleRate":24000,"pcmBytes":120000,"loop":false,"peak":0.56,"rms":0.1063287}, ogg: a51_ogg, mp3: a51_mp3},
  {...{"id":"fire_travel_2","group":"fire_travel","kind":"effect","duration":1.25,"channels":1,"sampleRate":24000,"pcmBytes":120000,"loop":false,"peak":0.56,"rms":0.1062281}, ogg: a52_ogg, mp3: a52_mp3},
  {...{"id":"flesh_1","group":"flesh","kind":"effect","duration":0.37,"channels":1,"sampleRate":24000,"pcmBytes":35520,"loop":false,"peak":0.56,"rms":0.0776689}, ogg: a53_ogg, mp3: a53_mp3},
  {...{"id":"flesh_2","group":"flesh","kind":"effect","duration":0.37,"channels":1,"sampleRate":24000,"pcmBytes":35520,"loop":false,"peak":0.56,"rms":0.0679348}, ogg: a54_ogg, mp3: a54_mp3},
  {...{"id":"flesh_3","group":"flesh","kind":"effect","duration":0.37,"channels":1,"sampleRate":24000,"pcmBytes":35520,"loop":false,"peak":0.56,"rms":0.0744348}, ogg: a55_ogg, mp3: a55_mp3},
  {...{"id":"latch_1","group":"latch","kind":"effect","duration":0.39,"channels":1,"sampleRate":24000,"pcmBytes":37440,"loop":false,"peak":0.56,"rms":0.0332623}, ogg: a56_ogg, mp3: a56_mp3},
  {...{"id":"latch_2","group":"latch","kind":"effect","duration":0.39,"channels":1,"sampleRate":24000,"pcmBytes":37440,"loop":false,"peak":0.56,"rms":0.0412106}, ogg: a57_ogg, mp3: a57_mp3},
  {...{"id":"leaves_1","group":"leaves","kind":"effect","duration":0.85,"channels":1,"sampleRate":24000,"pcmBytes":81600,"loop":false,"peak":0.56,"rms":0.0661058}, ogg: a58_ogg, mp3: a58_mp3},
  {...{"id":"leaves_2","group":"leaves","kind":"effect","duration":0.85,"channels":1,"sampleRate":24000,"pcmBytes":81600,"loop":false,"peak":0.56,"rms":0.0966123}, ogg: a59_ogg, mp3: a59_mp3},
  {...{"id":"leaves_3","group":"leaves","kind":"effect","duration":0.85,"channels":1,"sampleRate":24000,"pcmBytes":81600,"loop":false,"peak":0.56,"rms":0.0808466}, ogg: a60_ogg, mp3: a60_mp3},
  {...{"id":"miss_1","group":"miss","kind":"effect","duration":0.5,"channels":1,"sampleRate":24000,"pcmBytes":48000,"loop":false,"peak":0.56,"rms":0.0745044}, ogg: a61_ogg, mp3: a61_mp3},
  {...{"id":"miss_2","group":"miss","kind":"effect","duration":0.5,"channels":1,"sampleRate":24000,"pcmBytes":48000,"loop":false,"peak":0.56,"rms":0.0827617}, ogg: a62_ogg, mp3: a62_mp3},
  {...{"id":"parry_1","group":"parry","kind":"effect","duration":1.1,"channels":1,"sampleRate":24000,"pcmBytes":105600,"loop":false,"peak":0.56,"rms":0.0253426}, ogg: a63_ogg, mp3: a63_mp3},
  {...{"id":"parry_2","group":"parry","kind":"effect","duration":1.1,"channels":1,"sampleRate":24000,"pcmBytes":105600,"loop":false,"peak":0.56,"rms":0.0304603}, ogg: a64_ogg, mp3: a64_mp3},
  {...{"id":"parry_3","group":"parry","kind":"effect","duration":1.1,"channels":1,"sampleRate":24000,"pcmBytes":105600,"loop":false,"peak":0.56,"rms":0.0259096}, ogg: a65_ogg, mp3: a65_mp3},
  {...{"id":"respawn_1","group":"respawn","kind":"effect","duration":2.8,"channels":1,"sampleRate":24000,"pcmBytes":268800,"loop":false,"peak":0.481855,"rms":0.115}, ogg: a66_ogg, mp3: a66_mp3},
  {...{"id":"rest_1","group":"rest","kind":"effect","duration":2.5,"channels":1,"sampleRate":24000,"pcmBytes":240000,"loop":false,"peak":0.4471585,"rms":0.115}, ogg: a67_ogg, mp3: a67_mp3},
  {...{"id":"shield_1","group":"shield","kind":"effect","duration":0.69,"channels":1,"sampleRate":24000,"pcmBytes":66240,"loop":false,"peak":0.56,"rms":0.0343987}, ogg: a68_ogg, mp3: a68_mp3},
  {...{"id":"shield_2","group":"shield","kind":"effect","duration":0.69,"channels":1,"sampleRate":24000,"pcmBytes":66240,"loop":false,"peak":0.56,"rms":0.0365575}, ogg: a69_ogg, mp3: a69_mp3},
  {...{"id":"shield_3","group":"shield","kind":"effect","duration":0.69,"channels":1,"sampleRate":24000,"pcmBytes":66240,"loop":false,"peak":0.56,"rms":0.035055}, ogg: a70_ogg, mp3: a70_mp3},
  {...{"id":"shield_break_1","group":"shield_break","kind":"effect","duration":1.0,"channels":1,"sampleRate":24000,"pcmBytes":96000,"loop":false,"peak":0.56,"rms":0.0596442}, ogg: a71_ogg, mp3: a71_mp3},
  {...{"id":"step_dirt_1","group":"step_dirt","kind":"effect","duration":0.37,"channels":1,"sampleRate":24000,"pcmBytes":35520,"loop":false,"peak":0.56,"rms":0.0708449}, ogg: a72_ogg, mp3: a72_mp3},
  {...{"id":"step_dirt_2","group":"step_dirt","kind":"effect","duration":0.37,"channels":1,"sampleRate":24000,"pcmBytes":35520,"loop":false,"peak":0.56,"rms":0.0722642}, ogg: a73_ogg, mp3: a73_mp3},
  {...{"id":"step_dirt_3","group":"step_dirt","kind":"effect","duration":0.37,"channels":1,"sampleRate":24000,"pcmBytes":35520,"loop":false,"peak":0.56,"rms":0.070178}, ogg: a74_ogg, mp3: a74_mp3},
  {...{"id":"step_dirt_4","group":"step_dirt","kind":"effect","duration":0.37,"channels":1,"sampleRate":24000,"pcmBytes":35520,"loop":false,"peak":0.56,"rms":0.0722021}, ogg: a75_ogg, mp3: a75_mp3},
  {...{"id":"step_grass_1","group":"step_grass","kind":"effect","duration":0.42,"channels":1,"sampleRate":24000,"pcmBytes":40320,"loop":false,"peak":0.56,"rms":0.086029}, ogg: a76_ogg, mp3: a76_mp3},
  {...{"id":"step_grass_2","group":"step_grass","kind":"effect","duration":0.42,"channels":1,"sampleRate":24000,"pcmBytes":40320,"loop":false,"peak":0.56,"rms":0.0990712}, ogg: a77_ogg, mp3: a77_mp3},
  {...{"id":"step_grass_3","group":"step_grass","kind":"effect","duration":0.42,"channels":1,"sampleRate":24000,"pcmBytes":40320,"loop":false,"peak":0.56,"rms":0.0911759}, ogg: a78_ogg, mp3: a78_mp3},
  {...{"id":"step_grass_4","group":"step_grass","kind":"effect","duration":0.42,"channels":1,"sampleRate":24000,"pcmBytes":40320,"loop":false,"peak":0.56,"rms":0.0912245}, ogg: a79_ogg, mp3: a79_mp3},
  {...{"id":"step_stone_1","group":"step_stone","kind":"effect","duration":0.33,"channels":1,"sampleRate":24000,"pcmBytes":31680,"loop":false,"peak":0.56,"rms":0.0466251}, ogg: a80_ogg, mp3: a80_mp3},
  {...{"id":"step_stone_2","group":"step_stone","kind":"effect","duration":0.33,"channels":1,"sampleRate":24000,"pcmBytes":31680,"loop":false,"peak":0.56,"rms":0.0466792}, ogg: a81_ogg, mp3: a81_mp3},
  {...{"id":"step_stone_3","group":"step_stone","kind":"effect","duration":0.33,"channels":1,"sampleRate":24000,"pcmBytes":31680,"loop":false,"peak":0.56,"rms":0.0454735}, ogg: a82_ogg, mp3: a82_mp3},
  {...{"id":"step_stone_4","group":"step_stone","kind":"effect","duration":0.33,"channels":1,"sampleRate":24000,"pcmBytes":31680,"loop":false,"peak":0.56,"rms":0.0351694}, ogg: a83_ogg, mp3: a83_mp3},
  {...{"id":"step_wood_1","group":"step_wood","kind":"effect","duration":0.4,"channels":1,"sampleRate":24000,"pcmBytes":38400,"loop":false,"peak":0.5599999,"rms":0.0475644}, ogg: a84_ogg, mp3: a84_mp3},
  {...{"id":"step_wood_2","group":"step_wood","kind":"effect","duration":0.4,"channels":1,"sampleRate":24000,"pcmBytes":38400,"loop":false,"peak":0.56,"rms":0.0535491}, ogg: a85_ogg, mp3: a85_mp3},
  {...{"id":"step_wood_3","group":"step_wood","kind":"effect","duration":0.4,"channels":1,"sampleRate":24000,"pcmBytes":38400,"loop":false,"peak":0.56,"rms":0.051022}, ogg: a86_ogg, mp3: a86_mp3},
  {...{"id":"step_wood_4","group":"step_wood","kind":"effect","duration":0.4,"channels":1,"sampleRate":24000,"pcmBytes":38400,"loop":false,"peak":0.56,"rms":0.0567924}, ogg: a87_ogg, mp3: a87_mp3},
  {...{"id":"ui_1","group":"ui","kind":"effect","duration":0.14,"channels":1,"sampleRate":24000,"pcmBytes":13440,"loop":false,"peak":0.2295597,"rms":0.115}, ogg: a88_ogg, mp3: a88_mp3},
  {...{"id":"ui_2","group":"ui","kind":"effect","duration":0.14,"channels":1,"sampleRate":24000,"pcmBytes":13440,"loop":false,"peak":0.2282992,"rms":0.115}, ogg: a89_ogg, mp3: a89_mp3},
  {...{"id":"ui_cancel_1","group":"ui_cancel","kind":"effect","duration":0.3,"channels":1,"sampleRate":24000,"pcmBytes":28800,"loop":false,"peak":0.3070968,"rms":0.115}, ogg: a90_ogg, mp3: a90_mp3},
  {...{"id":"ui_confirm_1","group":"ui_confirm","kind":"effect","duration":0.37,"channels":1,"sampleRate":24000,"pcmBytes":35520,"loop":false,"peak":0.3334238,"rms":0.115}, ogg: a91_ogg, mp3: a91_mp3},
  {...{"id":"whoosh_heavy_1","group":"whoosh_heavy","kind":"effect","duration":0.68,"channels":1,"sampleRate":24000,"pcmBytes":65280,"loop":false,"peak":0.56,"rms":0.0863794}, ogg: a92_ogg, mp3: a92_mp3},
  {...{"id":"whoosh_heavy_2","group":"whoosh_heavy","kind":"effect","duration":0.68,"channels":1,"sampleRate":24000,"pcmBytes":65280,"loop":false,"peak":0.56,"rms":0.0813667}, ogg: a93_ogg, mp3: a93_mp3},
  {...{"id":"whoosh_heavy_3","group":"whoosh_heavy","kind":"effect","duration":0.68,"channels":1,"sampleRate":24000,"pcmBytes":65280,"loop":false,"peak":0.56,"rms":0.0995589}, ogg: a94_ogg, mp3: a94_mp3},
  {...{"id":"whoosh_light_1","group":"whoosh_light","kind":"effect","duration":0.39,"channels":1,"sampleRate":24000,"pcmBytes":37440,"loop":false,"peak":0.56,"rms":0.077157}, ogg: a95_ogg, mp3: a95_mp3},
  {...{"id":"whoosh_light_2","group":"whoosh_light","kind":"effect","duration":0.39,"channels":1,"sampleRate":24000,"pcmBytes":37440,"loop":false,"peak":0.56,"rms":0.0801204}, ogg: a96_ogg, mp3: a96_mp3},
  {...{"id":"whoosh_light_3","group":"whoosh_light","kind":"effect","duration":0.39,"channels":1,"sampleRate":24000,"pcmBytes":37440,"loop":false,"peak":0.56,"rms":0.0779699}, ogg: a97_ogg, mp3: a97_mp3},
  {...{"id":"room_ir","group":"room_ir","kind":"ir","duration":1.35,"channels":2,"sampleRate":24000,"pcmBytes":259200,"loop":false,"peak":0.42,"rms":0.0058514}, ogg: a98_ogg, mp3: a98_mp3},
  {...{"id":"music_duel","group":"duel","kind":"music","duration":64.0,"channels":2,"sampleRate":24000,"pcmBytes":12288000,"loop":true,"peak":0.4277878,"rms":0.092}, ogg: a99_ogg, mp3: a99_mp3},
  {...{"id":"music_forest","group":"forest","kind":"music","duration":120.0,"channels":2,"sampleRate":24000,"pcmBytes":23040000,"loop":true,"peak":0.4214759,"rms":0.092}, ogg: a100_ogg, mp3: a100_mp3},
  {...{"id":"music_meadow","group":"meadow","kind":"music","duration":120.0,"channels":2,"sampleRate":24000,"pcmBytes":23040000,"loop":true,"peak":0.47,"rms":0.0912492}, ogg: a101_ogg, mp3: a101_mp3},
  {...{"id":"music_rescue","group":"rescue","kind":"music","duration":35.0,"channels":2,"sampleRate":24000,"pcmBytes":6720000,"loop":false,"peak":0.4284733,"rms":0.092}, ogg: a102_ogg, mp3: a102_mp3},
  {...{"id":"music_royal","group":"royal","kind":"music","duration":64.0,"channels":2,"sampleRate":24000,"pcmBytes":12288000,"loop":true,"peak":0.47,"rms":0.0916889}, ogg: a103_ogg, mp3: a103_mp3},
  {...{"id":"music_title","group":"title","kind":"music","duration":60.0,"channels":2,"sampleRate":24000,"pcmBytes":11520000,"loop":true,"peak":0.4687807,"rms":0.092}, ogg: a104_ogg, mp3: a104_mp3},
  {...{"id":"silence","group":"silence","kind":"silence","duration":0.25,"channels":2,"sampleRate":24000,"pcmBytes":48000,"loop":true,"peak":0.0,"rms":0.0}, ogg: a105_ogg, mp3: a105_mp3},
] as const;
export const AUDIO_COMPRESSED_BYTES = 5932787;
