import assert from 'node:assert/strict';
import test from 'node:test';
import {
  WIDTH, HEIGHT, DIRS, RIGHT, createGame, stepMs, advance,
} from '../src/catalog_app/tools/neon_coil/frontend/core.js';

// A fixed, multi-food fixture, not generated by the implementation under test.
// It crosses four speed levels and ends by committing a fatal leftward tick.
const SEED = 305419896;
const TURNS = [
  [11, 2], [19, 1], [20, 0], [37, 3], [38, 2], [39, 3], [52, 2],
  [53, 1], [58, 2], [72, 1], [73, 0], [86, 1], [93, 0], [94, 3],
  [100, 2], [106, 3], [107, 0], [109, 3], [117, 2], [118, 1],
  [125, 2], [134, 3], [135, 0], [145, 3], [150, 0], [151, 1],
  [159, 2], [162, 3], [168, 2], [169, 1], [176, 0], [179, 1],
  [181, 2], [186, 3], [201, 2], [202, 1], [212, 2], [217, 1],
  [218, 0], [224, 1], [233, 0], [234, 3], [244, 2], [246, 3],
  [250, 0], [258, 3],
];
const EXPECTED_BODY = [
  [0, 4], [1, 4], [2, 4], [3, 4], [4, 4], [5, 4], [6, 4],
  [6, 5], [6, 6], [6, 7], [6, 8], [6, 9], [6, 10], [6, 11],
  [6, 12], [7, 12], [8, 12], [9, 12], [10, 12], [10, 11],
  [10, 10], [11, 10], [12, 10], [13, 10], [14, 10],
];

function replayFixture() {
  const game = createGame(SEED);
  let index = 0;
  let durationMs = 0;
  const placements = [{ tick: 0, food: [...game.food], rng: game.rng }];
  for (let tick = 1; tick <= 264; tick += 1) {
    durationMs += stepMs(game.foods);
    const direction = index < TURNS.length && TURNS[index][0] === tick
      ? TURNS[index++][1] : game.direction;
    const event = advance(game, direction);
    if (event.ate) placements.push({ tick, food: game.food && [...game.food], rng: game.rng });
  }
  return { seed: SEED, steps: 264, turns: TURNS, initial: createGame(SEED), game, durationMs, placements };
}

if (process.argv.includes('--fixture')) {
  // Used by the Python unittest parity check; emits JSON only, without TAP.
  console.log(JSON.stringify(replayFixture()));
} else {
  test('exports board dimensions, direction order, and exact initial cells', () => {
    assert.equal(WIDTH, 24);
    assert.equal(HEIGHT, 18);
    assert.equal(RIGHT, 1);
    assert.deepEqual(DIRS, [[0, -1], [1, 0], [0, 1], [-1, 0]]);
    assert.deepEqual(createGame(0), {
      body: [[8, 9], [7, 9], [6, 9], [5, 9], [4, 9]],
      direction: 1, food: [6, 17], rng: 1013904223, score: 0, foods: 0,
      steps: 0, alive: true, won: false, turns: [],
    });
  });

  test('unsigned seeds and initial LCG/free-cell row-major selection', () => {
    const cases = [
      [0, 1013904223, [6, 17]],
      [1, 1015568748, [13, 2]],
      [0xffffffff, 1012239698, [23, 13]],
      [SEED, 1967335287, [18, 10]],
    ];
    for (const [seed, rng, food] of cases) {
      const game = createGame(seed);
      assert.equal(game.rng, rng);
      assert.deepEqual(game.food, food);
      const occupied = new Set(game.body.map(([x, y]) => `${x},${y}`));
      const empty = [];
      for (let y = 0; y < HEIGHT; y += 1) {
        for (let x = 0; x < WIDTH; x += 1) {
          if (!occupied.has(`${x},${y}`)) empty.push([x, y]);
        }
      }
      assert.deepEqual(game.food, empty[rng % empty.length]);
    }
    assert.deepEqual(createGame(-1), createGame(0xffffffff));
    assert.deepEqual(createGame(2 ** 32), createGame(0));
    assert.deepEqual(createGame(2 ** 32 + 1), createGame(1));
  });

  test('games do not share mutable body or replay arrays', () => {
    const first = createGame(0);
    const second = createGame(0);
    first.body[0][0] = 100;
    first.turns.push([1, 0]);
    assert.deepEqual(second.body[0], [8, 9]);
    assert.deepEqual(second.turns, []);
  });

  test('first action is tick 1 and only committed changes enter turns', () => {
    const game = createGame(0);
    advance(game, 3); // opposite to right: ignored
    assert.equal(game.direction, 1);
    assert.equal(game.steps, 1);
    assert.deepEqual(game.turns, []);
    advance(game, 0);
    advance(game, 0);
    advance(game, 2); // opposite to up: ignored
    assert.deepEqual(game.turns, [[2, 0]]);
    assert.equal(game.direction, 0);
    advance(game, 3);
    assert.deepEqual(game.turns, [[2, 0], [5, 3]]);
  });

  test('malformed client direction input is ignored', () => {
    for (const invalid of [-1, 4, 1.2, NaN, '0', null, true, {}]) {
      const game = createGame(0);
      advance(game, invalid);
      assert.equal(game.direction, 1);
      assert.deepEqual(game.turns, []);
      assert.deepEqual(game.body[0], [9, 9]);
    }
  });

  test('food grows exactly one cell, scores 100, and consumes exactly one RNG draw', () => {
    const game = createGame(SEED);
    for (let i = 0; i < 10; i += 1) advance(game);
    const rng = game.rng;
    const event = advance(game, 2);
    assert.deepEqual(event, { ate: true, dead: false, won: false });
    assert.equal(game.body.length, 6);
    assert.equal(game.score, 100);
    assert.equal(game.foods, 1);
    assert.equal(game.rng, (1664525 * rng + 1013904223) >>> 0);
    assert.ok(!game.body.some(([x, y]) => x === game.food[0] && y === game.food[1]));
    const afterEating = game.rng;
    advance(game);
    assert.equal(game.rng, afterEating);
  });

  test('speed changes at five-food boundaries and never drops below 70 ms', () => {
    for (const [foods, expected] of [[0, 150], [4, 150], [5, 142], [9, 142],
      [10, 134], [49, 78], [50, 70], [100, 70], [427, 70]]) {
      assert.equal(stepMs(foods), expected);
    }
  });

  test('wall collision keeps last legal body and includes fatal tick', () => {
    const game = createGame(0);
    for (let i = 0; i < 15; i += 1) advance(game);
    const body = structuredClone(game.body);
    const rng = game.rng;
    assert.deepEqual(advance(game), { ate: false, dead: true, won: false });
    assert.equal(game.steps, 16);
    assert.equal(game.alive, false);
    assert.deepEqual(game.body, body);
    assert.equal(game.rng, rng);
    const ended = structuredClone(game);
    assert.deepEqual(advance(game, 0), { ate: false, dead: true, won: false });
    assert.deepEqual(game, ended);
  });

  test('a committed turn on the fatal tick remains in the replay', () => {
    const game = createGame(0);
    for (let tick = 1; tick <= 24; tick += 1) {
      advance(game, tick === 16 ? 2 : tick === 24 ? 1 : game.direction);
    }
    assert.equal(game.alive, false);
    assert.deepEqual(game.body[0], [23, 17]);
    assert.deepEqual(game.turns, [[16, 2], [24, 1]]);
    assert.equal(game.steps, 24);
  });

  test('moving into the vacating tail is legal when not eating', () => {
    const game = createGame(0);
    game.body = [[2, 2], [2, 3], [1, 3], [1, 2]];
    game.direction = 0;
    game.food = [10, 10];
    assert.deepEqual(advance(game, 3), { ate: false, dead: false, won: false });
    assert.deepEqual(game.body, [[1, 2], [2, 2], [2, 3], [1, 3]]);
    assert.equal(new Set(game.body.map(cell => cell.join(','))).size, 4);
  });

  test('eating cannot reuse the tail and body collision never moves cells', () => {
    const game = createGame(0);
    game.body = [[2, 2], [2, 3], [1, 3], [1, 2]];
    game.direction = 0;
    game.food = [1, 2]; // synthetic edge case: a growing tail would not vacate
    const body = structuredClone(game.body);
    assert.deepEqual(advance(game, 3), { ate: false, dead: true, won: false });
    assert.deepEqual(game.body, body);
    assert.equal(game.score, 0);
    const second = createGame(0);
    second.body = [[2, 2], [2, 3], [1, 3], [1, 2], [1, 1]];
    second.direction = 0;
    second.food = [10, 10];
    const before = structuredClone(second.body);
    assert.equal(advance(second, 3).dead, true);
    assert.deepEqual(second.body, before);
  });

  test('full board is victory without another food placement or RNG draw', () => {
    const game = createGame(0);
    const path = [];
    for (let y = 0; y < HEIGHT; y += 1) {
      for (let index = 0; index < WIDTH; index += 1) {
        path.push([y % 2 ? WIDTH - 1 - index : index, y]);
      }
    }
    game.body = path.slice(0, -1).reverse();
    game.direction = 3;
    game.food = path.at(-1);
    game.foods = 426;
    game.score = 42600;
    const rng = game.rng;
    assert.deepEqual(advance(game), { ate: true, dead: false, won: true });
    assert.equal(game.body.length, 432);
    assert.equal(game.score, 42700);
    assert.equal(game.foods, 427);
    assert.equal(game.food, null);
    assert.equal(game.alive, false);
    assert.equal(game.won, true);
    assert.equal(game.rng, rng);
    const ended = structuredClone(game);
    assert.deepEqual(advance(game), { ate: false, dead: false, won: true });
    assert.deepEqual(game, ended);
  });

  test('fixed twenty-food replay matches known final geometry, RNG, score and turns', () => {
    const fixture = replayFixture();
    assert.equal(fixture.game.score, 2000);
    assert.equal(fixture.game.foods, 20);
    assert.equal(fixture.game.steps, 264);
    assert.equal(fixture.game.alive, false);
    assert.equal(fixture.game.won, false);
    assert.equal(fixture.game.direction, 3);
    assert.equal(fixture.game.rng, 1929958827);
    assert.deepEqual(fixture.game.food, [4, 10]);
    assert.deepEqual(fixture.game.body, EXPECTED_BODY);
    assert.deepEqual(fixture.game.turns, TURNS);
    assert.equal(fixture.placements.length, 21);
    assert.ok(fixture.durationMs < 264 * 150);
  });

  test('core has no implicit tick cap; a host can end a bounded 18000-tick session', () => {
    const game = createGame(0);
    const cycle = [1, 0, 3, 2];
    for (let tick = 1; tick <= 18001; tick += 1) {
      advance(game, cycle[Math.floor((tick - 1) / 4) % 4]);
    }
    assert.equal(game.steps, 18001);
    assert.equal(game.score, 0);
    assert.equal(game.alive, true);
    assert.equal(game.won, false);
  });
}
