import {build} from 'esbuild';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve,dirname} from 'node:path';
import {gzipSync} from 'node:zlib';
const here=import.meta.dirname,tool=resolve(here,'..');
const assetPlugin={name:'embedded-assets',setup(b){b.onResolve({filter:/\?url$/},a=>({path:resolve(a.resolveDir,a.path.replace(/\?url$/,'')),namespace:'asset'}));b.onLoad({filter:/.*/,namespace:'asset'},async a=>{let path=a.path;if(path.includes('@fontsource/')){const name=path.slice(path.indexOf('@fontsource/'));path=resolve(here,'node_modules',name);}const ext=path.split('.').at(-1),types={png:'image/png',jpg:'image/jpeg',glb:'model/gltf-binary',ogg:'audio/ogg',mp3:'audio/mpeg',woff2:'font/woff2'};const bytes=await readFile(path);return{contents:`export default ${JSON.stringify('data:'+(types[ext]||'application/octet-stream')+';base64,'+bytes.toString('base64'))}`,loader:'js'};});b.onResolve({filter:/\?worker-source$/},a=>({path:resolve(a.resolveDir,a.path.replace(/\?worker-source$/,'')),namespace:'worker-source'}));b.onLoad({filter:/.*/,namespace:'worker-source'},async a=>{const out=await build({entryPoints:[a.path],bundle:true,minify:true,format:'iife',platform:'browser',target:'es2022',write:false});return{contents:`export default ${JSON.stringify(out.outputFiles[0].text)}`,loader:'js'};});}};
const result=await build({entryPoints:[resolve(here,'main.ts')],outfile:resolve(tool,'app.js'),bundle:true,minify:true,format:'esm',platform:'browser',target:'es2022',legalComments:'inline',charset:'utf8',write:false,metafile:true,plugins:[assetPlugin],loader:{'.ogg':'dataurl','.mp3':'dataurl','.png':'dataurl','.glb':'dataurl','.woff2':'dataurl'},logLevel:'info'});
const code=result.outputFiles[0].text.replace(/<\/script/gi,'<\\/script');await writeFile(resolve(tool,'app.js'),`/* The Gloaming Road — generated from frontend/main.ts. All game assets local and inlined. */\n${code}`);
const html=await readFile(resolve(tool,'app.html'),'utf8');const standalone=html.replace('<!-- app.js -->',()=>`<script type="module">${code}</script>`);await mkdir(resolve(here,'dist'),{recursive:true});await writeFile(resolve(here,'dist/index.html'),standalone);
const packages=new Set();for(const p of Object.keys(result.metafile.inputs)){if(!p.includes('node_modules/'))continue;const part=p.split('node_modules/').at(-1).split('/');packages.add(part[0].startsWith('@')?part.slice(0,2).join('/'):part[0]);}
const notices=['THIRD-PARTY NOTICES — THE GLOAMING ROAD\nOriginal artwork/audio provenance lives alongside these notices.'];for(const name of [...packages].sort()){const base=resolve(here,'node_modules',name);let found='';for(const filename of ['LICENSE','LICENSE.md','LICENSE.txt','license','license.md','OFL.txt']){try{found=await readFile(resolve(base,filename),'utf8');break;}catch(e){if(e.code!=='ENOENT')throw e;}}if(!found)continue;notices.push(`\n===== ${name} =====\n${found}`);}for(const name of ['@fontsource/cormorant-garamond','@fontsource/inter']){const license=await readFile(resolve(here,'node_modules',name,'LICENSE'),'utf8');notices.push(`\n===== ${name} =====\n${license}`);}await writeFile(resolve(tool,'THIRD_PARTY_NOTICES.txt'),notices.join('\n'));
console.log(`Single HTML: ${(Buffer.byteLength(standalone)/1048576).toFixed(2)} MiB; gzip ${(gzipSync(standalone).byteLength/1048576).toFixed(2)} MiB. Runtime network dependencies: none.`);
