import * as THREE from 'three';
import {Physics,type Capsule,type BodyTag} from './physics';
import {TUNE,type Sector,type EnemyKind,type SaveRecord,type RecentEncounter} from './state';
import type {InputFrame} from './input';
import type {CharacterLibrary,CharacterView} from './characters';
import type {GameAudio} from './audio';
import type {Encounter,TerrainAPI} from './world-contract';
import {Effects} from './effects';
import type {Castle} from './castle';
export interface Attack {heavy:boolean;sector:Sector;time:number;windup:number;active:number;recovery:number;hit:Set<string>;sounded:boolean;yaw:number;}
export interface Player {body:Capsule;pos:THREE.Vector3;yaw:number;pitch:number;health:number;stamina:number;sector:Sector;guard:boolean;guardAt:number;spent:number;stagger:number;charge:number|null;attack:Attack|null;dodge:number;dodgeX:number;dodgeZ:number;feint:number;velocity:THREE.Vector3;}
interface Enemy {id:string;kind:EnemyKind;view:CharacterView;body:Capsule|null;pos:THREE.Vector3;home:THREE.Vector3;health:number;stamina:number;state:'idle'|'notice'|'approach'|'telegraph'|'attack'|'recover'|'defend'|'stagger'|'dead'|'dodge'|'charge';t:number;cooldown:number;sector:Sector;heavy:boolean;attack:Attack|null;lastBlade:{base:THREE.Vector3;tip:THREE.Vector3}|null;yaw:number;sawWindup:number;decided:boolean;event?:number;alert:boolean;rollX:number;rollZ:number;foot:number;royal:boolean;}
interface Projectile {mesh:THREE.Group;pos:THREE.Vector3;velocity:THREE.Vector3;life:number;owner:string;fire:boolean;}
const sectors:Sector[]=['high','left','right','low'];
const mirror=(s:Sector):Sector=>s==='left'?'right':s==='right'?'left':s;
const turn=(a:number,b:number,t:number)=>a+Math.atan2(Math.sin(b-a),Math.cos(b-a))*Math.min(1,t);
const total=(a:Attack)=>a.windup+a.active+a.recovery;
const makeAttack=(heavy:boolean,sector:Sector,yaw:number,wind?:number):Attack=>{const t=heavy?TUNE.heavy:TUNE.light;return{heavy,sector,yaw,time:0,windup:wind??t.windup,active:t.active,recovery:t.recovery,hit:new Set(),sounded:false};};
export class Combat {
  enemies=new Map<string,Enemy>();projectiles:Projectile[]=[];player:Player;private lastPlayerBlade:{base:THREE.Vector3;tip:THREE.Vector3}|null=null;private recent=new Map<string,RecentEncounter>();private syncAt=0;private time=0;private origin={x:0,z:0};private shieldBreakUntil=0;private lastThreat=0;
  constructor(private physics:Physics,private library:CharacterLibrary,private scene:THREE.Scene,private audio:GameAudio,private effects:Effects,private terrain:TerrainAPI,private castle:Castle,private save:SaveRecord,player:Player,private weapon:()=>{base:THREE.Vector3;tip:THREE.Vector3},private playerPose:(name:string,t:number)=>void,private onDefeat:(id:string)=>void,private onHit:(damage:number)=>void){this.player=player;for(const r of save.recent)this.recent.set(r.id,r);}
  get threat(){return this.time-this.lastThreat<4;}
  get royalThreat(){return [...this.enemies.values()].some(e=>e.royal&&e.alert&&e.state!=='dead');}
  get activeCount(){return this.enemies.size;}
  get holdsCastlePhysics(){const f=this.castle.feature;return [...this.enemies.values()].some(e=>e.body&&Math.abs(e.pos.x+this.origin.x-f.x)<32&&Math.abs(e.pos.z+this.origin.z-f.z)<42);}
  get nearest(){let best:Enemy|null=null,dist=8;for(const e of this.enemies.values()){if(e.state==='dead')continue;const d=e.pos.distanceTo(this.player.pos);if(d<dist){dist=d;best=e;}}return best;}
  expenditure(cost:number){if(this.player.stamina<cost)return false;this.player.stamina-=cost;this.player.spent=this.time;return true;}
  playerInput(f:InputFrame,dt:number,time:number){this.time=time;const p=this.player;p.sector=f.sector;p.stagger=Math.max(0,p.stagger-dt);p.feint=Math.max(0,p.feint-dt);p.dodge=Math.max(0,p.dodge-dt);const can=p.stagger<=0&&p.dodge<=0&&p.feint<=0;
    if(f.guardDown&&can){const cancellable=p.charge!==null?p.charge<.42:p.attack&&p.attack.time<p.attack.windup*.72;if(cancellable&&this.expenditure(TUNE.feint)){p.charge=null;p.attack=null;p.feint=.22;this.playerPose('feint',0);this.audio.play('cloth');}p.guardAt=time;}
    p.guard=f.guard&&!p.attack&&p.charge===null&&can&&p.feint<=0&&time>this.shieldBreakUntil;
    if(f.attackDown&&!p.attack&&p.charge===null&&can&&this.expenditure(TUNE.light.cost)){p.charge=0;p.guard=false;}
    if(p.charge!==null){p.charge+=dt;this.playerPose(`heavy-${p.sector}`,Math.min(.46,p.charge));}
    if(f.attackUp&&p.charge!==null){const heavy=p.charge>=.36&&this.expenditure(TUNE.heavy.cost-TUNE.light.cost);p.attack=makeAttack(heavy,p.sector,p.yaw);p.attack.time=Math.min(p.charge,p.attack.windup-.015);p.charge=null;p.guard=false;this.lastPlayerBlade=null;}
    if(f.dodge&&can&&!p.attack&&p.charge===null&&this.expenditure(TUNE.dodgeCost)){p.dodge=TUNE.dodgeTime;let x=f.x,z=f.z;if(Math.hypot(x,z)<.1)z=1;const l=Math.hypot(x,z);p.dodgeX=(x/l*Math.cos(p.yaw)+z/l*Math.sin(p.yaw))*TUNE.dodgeDistance/TUNE.dodgeTime;p.dodgeZ=(-x/l*Math.sin(p.yaw)+z/l*Math.cos(p.yaw))*TUNE.dodgeDistance/TUNE.dodgeTime;this.audio.play('cloth');}
    if(time-p.spent>TUNE.regenDelay)p.stamina=Math.min(100,p.stamina+TUNE.regen*dt*(p.guard?.42:1));
  }
  sync(defs:Encounter[],clock:number,bloodNight:number|undefined,ready:(x:number,z:number)=>boolean){if(clock-this.syncAt<.5)return;this.syncAt=clock;const p=this.player.pos,px=p.x+this.origin.x,pz=p.z+this.origin.z;
    for(const e of this.enemies.values()){const d=e.pos.distanceTo(p);if(d>98&&(e.state==='dead'||!e.alert||d>125)){this.remember(e,clock);this.removeEnemy(e.id);}}
    if(this.castle.near(px,pz)){for(let i=0;i<this.save.mission.guardIds.length;i++){const id=this.save.mission.guardIds[i];if(this.save.mission.defeated.includes(id)||this.enemies.has(id))continue;const home=this.castle.guards()[i];if(Math.hypot(home.x-px,home.z-pz)<78&&ready(home.x,home.z))this.spawn(id,'elite',home.x,home.z,home.y,undefined,true);}}
    const candidates=[...defs];if(bloodNight!==undefined){for(const d of defs){if(d.kind==='archer'||d.kind==='mage')candidates.push({...d,id:`${d.id}:blood:${bloodNight}`,kind:'mage',event:bloodNight});}}
    for(const r of this.recent.values()){if(r.kind!=='elite'&&!r.dead&&clock-r.seen<TUNE.respawnAfter&&!candidates.some(d=>d.id===r.id))candidates.push({id:r.id,kind:r.kind,x:r.homeX??r.x,z:r.homeZ??r.z,...(r.event===undefined?{}:{event:r.event})});}
    candidates.sort((a,b)=>Math.hypot(a.x-px,a.z-pz)-Math.hypot(b.x-px,b.z-pz));
    for(const d of candidates){if(this.enemies.size>=TUNE.maxActors)break;if(this.enemies.has(d.id))continue;const recent=this.recent.get(d.id),restore=recent&&!recent.dead&&clock-recent.seen<TUNE.respawnAfter,gx=restore?recent.x:d.x,gz=restore?recent.z:d.z;const dist=Math.hypot(gx-px,gz-pz);if(dist>64||!ready(gx,gz)||Math.hypot(gx-this.terrain.features.spawn.x,gz-this.terrain.features.spawn.z)<34||Math.hypot(gx-this.save.recovery.x,gz-this.save.recovery.z)<16)continue;if(recent?.dead&&clock-recent.seen<TUNE.respawnAfter)continue;if(d.event!==undefined&&!restore){const dx=(d.x-px)/Math.max(1,dist),dz=(d.z-pz)/Math.max(1,dist);if(dist<28||dx*-Math.sin(this.player.yaw)+dz*-Math.cos(this.player.yaw)>.15)continue;}if(d.event!==undefined&&d.event!==bloodNight&&!restore)continue;this.spawn(d.id,d.kind,d.x,d.z,this.terrain.height(d.x,d.z),d.event,false);}
  }
  private spawn(id:string,kind:EnemyKind,x:number,z:number,y:number,event:number|undefined,royal:boolean){const recent=this.recent.get(id);const restore=recent&&!recent.dead&&this.time-recent.seen<TUNE.respawnAfter;let xx=(restore?recent.x:x)-this.origin.x,zz=(restore?recent.z:z)-this.origin.z;const gx=xx+this.origin.x,gz=zz+this.origin.z;if(!this.physics.ready(gx,gz))return;const f=this.castle.feature;const floorAt=(a:number,b:number)=>Math.abs(a-f.x)<27&&Math.abs(b-f.z)<36?this.castle.floor(a,b):this.terrain.height(a,b);const support=floorAt(gx,gz);let yy=restore?(typeof recent.y==='number'&&Number.isFinite(recent.y)?Math.max(recent.y,support):support):Math.max(y,support);
    if(event!==undefined){
      // Blood-night additions share an encounter anchor, not another body's space.
      // Resolve only a small, bounded local placement; never move an existing actor.
      const bx=xx,bz=zz;let placed=false;
      for(const [dx,dz]of [[0,0],[1.1,0],[-1.1,0],[0,1.1],[0,-1.1],[1.1,1.1],[-1.1,1.1],[1.1,-1.1],[-1.1,-1.1]]){const ax=bx+dx,az=bz+dz,h=dx||dz?floorAt(ax+this.origin.x,az+this.origin.z):yy;if((dx||dz)&&Math.abs(h-yy)>.65)continue;if(!this.physics.ready(ax+this.origin.x,az+this.origin.z))continue;const px=ax-this.player.pos.x,pz=az-this.player.pos.z,pd=Math.hypot(px,pz);if(!restore&&(pd<28||px*-Math.sin(this.player.yaw)+pz*-Math.cos(this.player.yaw)>.15*pd))continue;if(Math.abs(this.player.pos.y-h)<1.8&&Math.hypot(this.player.pos.x-ax,this.player.pos.z-az)<.85)continue;if([...this.enemies.values()].some(e=>e.body&&Math.abs(e.pos.y-h)<1.8&&Math.hypot(e.pos.x-ax,e.pos.z-az)<.85)||!this.physics.capsuleSpace(ax,h,az))continue;xx=ax;zz=az;yy=h;placed=true;break;}
      if(!placed)return;
    }
    const view=this.library.create(kind);view.root.position.set(xx,yy,zz);this.scene.add(view.root);const hp=kind==='elite'?104:kind==='shield'?88:kind==='swordsman'?80:kind==='mage'?64:56;const enemy:Enemy={id,kind,view,body:this.physics.capsule(xx,yy+.04,zz,id),pos:new THREE.Vector3(xx,yy,zz),home:new THREE.Vector3(x-this.origin.x,y,z-this.origin.z),health:restore?recent.health:hp,stamina:80,state:'idle',t:Math.random()*2,cooldown:.5+Math.random(),sector:'high',heavy:false,attack:null,lastBlade:null,yaw:Math.random()*Math.PI*2,sawWindup:0,decided:false,event,alert:false,rollX:0,rollZ:0,foot:0,royal};this.enemies.set(id,enemy);view.play('idle');}
  update(dt:number,time:number){this.time=time;const p=this.player;const committed=new Set([...this.enemies.values()].filter(e=>e.state==='telegraph'||e.state==='attack'||e.state==='charge').map(e=>e.id));
    // Releasing a bow must not free a third attack while its arrow is incoming.
    // Spent projectiles moving away beyond splash range no longer hold a slot.
    for(const shot of this.projectiles){const dx=p.pos.x-shot.pos.x,dy=p.pos.y+1.2-shot.pos.y,dz=p.pos.z-shot.pos.z;if(dx*shot.velocity.x+dy*shot.velocity.y+dz*shot.velocity.z>0||dx*dx+dy*dy+dz*dz<16)committed.add(shot.owner);}
    let slots=Math.max(0,2-committed.size);
    for(const e of this.enemies.values()){e.t+=dt;e.cooldown-=dt;if(e.state==='dead'){e.view.pose('death',Math.min(e.t,1.4));continue;}if(e.body)e.pos.copy(this.physics.feet(e.body));e.view.root.position.copy(e.pos);const gx=e.pos.x+this.origin.x,gz=e.pos.z+this.origin.z;
      // Visual/encounter retention extends past the bounded collision ring.
      // Keep distant silhouettes dormant instead of integrating a fall into void.
      if(!this.physics.ready(gx,gz)||!this.physics.ready(gx-.75,gz-.75)||!this.physics.ready(gx+.75,gz+.75)){if(e.body){e.body.vy=0;e.body.body.setNextKinematicTranslation(e.body.body.translation());}e.attack=null;e.lastBlade=null;e.alert=false;e.sawWindup=0;e.decided=false;e.state='idle';e.t=0;e.cooldown=Math.max(.35,e.cooldown);e.view.play('idle');e.view.update(dt);continue;}
      const to=p.pos.clone().sub(e.pos),distance=Math.hypot(to.x,to.z);const visible=distance<26&&!this.physics.wallBetween(e.pos.clone().add(new THREE.Vector3(0,1.5,0)),p.pos.clone().add(new THREE.Vector3(0,1.3,0)));const facing=to.x*Math.sin(e.yaw)+to.z*Math.cos(e.yaw);if(!e.alert&&visible&&(distance<9||facing>distance*.12)){e.alert=true;e.state='notice';e.t=0;e.cooldown=.7;this.audio.play(e.kind==='mage'?'cloth':'armor-rustle',e.pos,.32);}if(e.alert&&distance<35)this.lastThreat=time;if(e.alert&&distance>36&&e.pos.distanceTo(e.home)>42){e.alert=false;e.state='approach';}
      if(e.state==='stagger'){e.view.pose('stagger',Math.min(e.t,.6));if(e.t>.62){e.state='recover';e.t=0;e.cooldown=.35;}this.moveEnemy(e,-Math.sin(e.yaw)*.2,-Math.cos(e.yaw)*.2,dt);continue;}
      if(e.state==='dodge'){e.view.pose('dodge',Math.min(e.t,.7));this.moveEnemy(e,e.t<.28?e.rollX:0,e.t<.28?e.rollZ:0,dt);if(e.t>.67){e.state='recover';e.t=0;e.cooldown=.36;}continue;}
      if(e.state==='notice'){e.view.play('idle');e.view.update(dt);if(e.t>.65){e.state='approach';e.t=0;}this.moveEnemy(e,0,0,dt);continue;}
      if(e.state==='telegraph'||e.state==='attack'){this.enemyAttack(e,dt);this.moveEnemy(e,0,0,dt);continue;}
      if(e.state==='charge'){this.rangedAttack(e,dt);this.moveEnemy(e,0,0,dt);continue;}
      if(e.state==='recover'){if((e.kind==='archer'||e.kind==='mage')&&e.t<.72)e.view.pose(e.kind==='mage'?'cast':'release',e.t+(e.kind==='mage'?.24:.12));else{e.view.play('idle',.12);e.view.update(dt);}this.moveEnemy(e,0,0,dt);if(e.cooldown<=0){e.state='approach';e.t=0;}continue;}
      const targetYaw=Math.atan2(to.x,to.z);if(e.alert)e.yaw=turn(e.yaw,targetYaw,dt*7);e.view.root.rotation.y=e.yaw;
      if(!e.alert){if(e.pos.distanceTo(e.home)>2){const home=e.home.clone().sub(e.pos);const l=Math.hypot(home.x,home.z);e.yaw=turn(e.yaw,Math.atan2(home.x,home.z),dt*4);e.view.root.rotation.y=e.yaw;this.moveEnemy(e,home.x/l*1.4,home.z/l*1.4,dt);e.view.play('walk');}else{this.moveEnemy(e,0,0,dt);e.view.play('idle');}e.view.update(dt);continue;}
      if(visible&&(p.attack||p.charge!==null)){if(!e.sawWindup)e.sawWindup=time;}else{if(e.state==='defend'){e.state='recover';e.t=0;e.cooldown=.32;}e.sawWindup=0;e.decided=false;}
      if(e.sawWindup&&visible&&time-e.sawWindup>TUNE.enemyReaction&&!e.decided&&distance<3.2){e.decided=true;const chance=e.royal?.57:e.kind==='shield'?.66:.30;if(Math.random()<chance){e.state='defend';e.sector=p.attack?.sector??p.sector;e.t=0;}else if(e.royal&&Math.random()<.22){e.state='dodge';e.t=0;e.rollX=-to.x/Math.max(1,distance)*2.6;e.rollZ=-to.z/Math.max(1,distance)*2.6;}}
      if(e.state==='defend'){e.view.pose(`guard-${mirror(e.sector)}`,Math.min(.35,e.t));this.moveEnemy(e,0,0,dt);if(e.t>.85){e.state='recover';e.cooldown=.3;e.t=0;}continue;}
      const ranged=e.kind==='archer'||e.kind==='mage';const range=ranged?(e.kind==='archer'?18:13):1.65;
      if(distance<range&&visible&&e.cooldown<=0&&(slots>0||committed.has(e.id))){if(!committed.has(e.id)){slots--;committed.add(e.id);}e.sector=sectors[Math.floor(Math.random()*4)];e.heavy=Math.random()<(e.royal?.30:.18);e.t=0;if(ranged){e.state='charge';this.audio.play(e.kind==='mage'?'fire-charge':'bow-draw',e.pos,.85);}else {e.state='telegraph';e.attack=makeAttack(e.heavy,e.sector,e.yaw,e.royal?(e.heavy?.64:.48):(e.heavy?.8:.62));e.lastBlade=null;}continue;}
      let vx=0,vz=0;if(distance>range*.92){const dir=to.clone().normalize();vx=dir.x*(ranged?1.65:2.25);vz=dir.z*(ranged?1.65:2.25);}else if(ranged&&distance<5){vx=-to.x/Math.max(distance,.1)*1.6;vz=-to.z/Math.max(distance,.1)*1.6;}else if(!ranged&&distance<1.2){vx=-to.x/Math.max(distance,.1)*.8;vz=-to.z/Math.max(distance,.1)*.8;}else{const sign=e.id.charCodeAt(e.id.length-1)%2?1:-1;vx=to.z/Math.max(distance,.1)*.45*sign;vz=-to.x/Math.max(distance,.1)*.45*sign;}
      for(const other of this.enemies.values()){if(other===e||other.state==='dead')continue;const d=e.pos.clone().sub(other.pos),l=Math.hypot(d.x,d.z);if(l<1.3&&l>.01){vx+=d.x/l*(1.3-l)*2;vz+=d.z/l*(1.3-l)*2;}}
      // Local obstacle steering shares actual ray/collider geometry. Inside the
      // castle an authored entrance/stair graph supplies a waypoint when occluded.
      const start=e.pos.clone().add(new THREE.Vector3(0,.9,0));if(this.physics.wallBetween(start,start.clone().add(new THREE.Vector3(vx,0,vz).normalize().multiplyScalar(1.05)))){const nodes=this.castle.navigation().map(n=>new THREE.Vector3(n.x-this.origin.x,e.pos.y+.9,n.z-this.origin.z));const options=nodes.filter(n=>!this.physics.wallBetween(start,n)&&start.distanceTo(n)>1.5).sort((a,b)=>a.distanceTo(p.pos)-b.distanceTo(p.pos));if(e.royal&&options.length){const way=options[0].clone().sub(start).normalize();vx=way.x*1.8;vz=way.z*1.8;}else{const old=vx;vx=-vz;vz=old;}}
      this.moveEnemy(e,vx,vz,dt);e.view.play(Math.hypot(vx,vz)>.2?'walk':'idle',.15);e.view.update(dt);e.foot+=Math.hypot(vx,vz)*dt;if(e.foot>1.5&&distance<18){e.foot=0;this.audio.play(this.castle.inside(e.pos.x+this.origin.x,e.pos.y,e.pos.z+this.origin.z)?'step-stone':'step-grass',e.pos,.25);}
    }
    this.updatePlayerAttack(dt);this.updateProjectiles(dt);
  }
  private moveEnemy(e:Enemy,x:number,z:number,dt:number){if(!e.body)return;const gx=e.pos.x+this.origin.x+x*dt,gz=e.pos.z+this.origin.z+z*dt;if(!this.physics.ready(gx,gz)){e.body.vy=0;e.body.body.setNextKinematicTranslation(e.body.body.translation());return;}this.physics.move(e.body,x*dt,z*dt,dt);}
  private enemyAttack(e:Enemy,dt:number){const a=e.attack!;a.time+=dt;e.view.root.rotation.y=a.yaw;const phase=a.time<a.windup?'telegraph':a.time<a.windup+a.active?'attack':'recover';const clipTime=a.time<a.windup?a.time/a.windup*(a.heavy?.52:.24):a.time-a.windup+(a.heavy?.52:.24);e.view.pose(`${a.heavy?'heavy':'light'}-${mirror(a.sector)}`,clipTime);const blade=e.view.weaponPoints();
    if(phase==='attack'){e.state='attack';if(!a.sounded){a.sounded=true;this.audio.play(a.heavy?'swing-heavy':'swing-light',e.pos,.7);}if(e.lastBlade)this.physics.bladeSweep(e.lastBlade,blade,e.id,(tag,point)=>{if(tag.kind==='player'&&!a.hit.has('player')&&!this.physics.wallBetween(e.pos.clone().add(new THREE.Vector3(0,1.3,0)),point)){a.hit.add('player');this.damagePlayer(e,a,point);}});}
    // A royal feint cancels only early telegraph, visibly recovering rather than
    // reading future input. It creates an opening and costs its own stamina.
    if(e.royal&&phase==='telegraph'&&a.time>.24&&a.time<.26&&this.player.guard&&Math.random()<.15){e.attack=null;e.state='recover';e.cooldown=.35;e.t=0;e.view.play('feint',.04);return;}
    e.lastBlade={base:blade.base.clone(),tip:blade.tip.clone()};if(a.time>=total(a)){e.attack=null;e.state='recover';e.cooldown=e.royal?.40:.65;e.t=0;e.lastBlade=null;}
  }
  private updatePlayerAttack(dt:number){const p=this.player;if(p.attack){const a=p.attack;a.time+=dt;this.playerPose(`${a.heavy?'heavy':'light'}-${a.sector}`,a.time);const blade=this.weapon();if(a.time>=a.windup&&a.time<a.windup+a.active){if(!a.sounded){a.sounded=true;this.audio.play(a.heavy?'swing-heavy':'swing-light');}if(this.lastPlayerBlade){this.effects.slash(this.lastPlayerBlade,blade);this.physics.bladeSweep(this.lastPlayerBlade,blade,'player',(tag,point)=>{const id=tag.id??tag.kind;if(a.hit.has(id))return;if(point.distanceTo(p.pos.clone().add(new THREE.Vector3(0,1.25,0)))>TUNE.reach+.2)return;if(this.physics.wallBetween(p.pos.clone().add(new THREE.Vector3(0,1.35,0)),point))return;a.hit.add(id);if(tag.kind==='enemy'&&tag.id){const enemy=this.enemies.get(tag.id);if(enemy)this.damageEnemy(enemy,a,point);}else if(tag.kind!=='player'&&tag.kind!=='ground'){this.effects.impact(point,'stone');this.audio.play('impact-stone',point,.6);a.time=a.windup+a.active;}});}}this.lastPlayerBlade={base:blade.base.clone(),tip:blade.tip.clone()};if(a.time>=total(a)){p.attack=null;this.lastPlayerBlade=null;}}
    else if(p.charge===null){this.lastPlayerBlade=null;if(p.stagger>0)this.playerPose('stagger',.6-p.stagger);else if(p.dodge>0)this.playerPose('dodge',TUNE.dodgeTime-p.dodge);else if(p.feint>0)this.playerPose('feint',.22-p.feint);else if(p.guard)this.playerPose(`guard-${p.sector}`,Math.min(.3,this.time-p.guardAt));else this.playerPose('idle',this.time%4);}}
  private damageEnemy(e:Enemy,a:Attack,point:THREE.Vector3){if(e.state==='dead')return;const keepsCommitment=e.royal&&!a.heavy&&!!e.attack&&(e.state==='telegraph'||e.state==='attack');const facing=new THREE.Vector3(Math.sin(e.yaw),0,Math.cos(e.yaw));const toward=this.player.pos.clone().sub(e.pos).normalize();const facingOK=facing.dot(toward)>.45;const directed=e.state==='defend'&&e.sector===a.sector&&facingOK;const shield=e.kind==='shield'&&e.state!=='attack'&&e.state!=='telegraph'&&e.state!=='recover'&&e.state!=='stagger'&&facing.dot(toward)>.78&&point.y>e.pos.y+.45&&point.y<e.pos.y+1.6;
    if((directed||shield)&&e.stamina>0){e.stamina-=a.heavy?32:13;const parry=directed&&e.t<TUNE.parry,blade=e.view.weaponPoints(),contact=shield?point:blade.base.clone().lerp(blade.tip,.4);this.effects.impact(contact,'steel',a.heavy);this.audio.play(shield?'shield':parry?'parry':'block',contact);if(parry){this.player.attack=null;this.player.stagger=.27;this.lastPlayerBlade=null;e.cooldown=.1;}else if(a.heavy||e.stamina<=0){e.state='stagger';e.t=0;e.attack=null;}return;}
    e.health-=a.heavy?40:24;e.alert=true;this.lastThreat=this.time;this.effects.impact(point,'blood',a.heavy);this.audio.play(e.kind==='mage'||e.kind==='archer'?'hit-flesh':'armor',point,.85);if(e.health<=0){e.health=0;e.state='dead';e.t=0;e.attack=null;e.alert=false;if(e.body){this.physics.removeCapsule(e.body);e.body=null;}e.view.play('death',.06);this.audio.play('death-enemy',e.pos,.75);this.effects.pool(e.pos);this.remember(e,this.time);if(e.royal)this.onDefeat(e.id);}else if(!keepsCommitment){e.state='stagger';e.t=0;e.attack=null;e.lastBlade=null;e.cooldown=.65;const push=e.pos.clone().sub(this.player.pos).normalize().multiplyScalar(a.heavy?.24:.09);if(e.body)this.physics.move(e.body,push.x,push.z,TUNE.step);}}
  private damagePlayer(enemy:Enemy|null,a:Attack|null,point:THREE.Vector3,raw=0){const p=this.player;if(p.health<=0)return;const attacker=enemy?.pos??point;const direction=attacker.clone().sub(p.pos).normalize();const facing=new THREE.Vector3(-Math.sin(p.yaw),0,-Math.cos(p.yaw)).dot(direction)>.4;const block=p.guard&&facing&&(!a||p.sector===a.sector)&&p.stamina>0;const heavy=a?.heavy??false;
    if(block){const parry=!!a&&this.time-p.guardAt<=TUNE.parry;const cost=heavy?TUNE.heavyBlock:TUNE.block;p.stamina=Math.max(0,p.stamina-(parry?cost*.4:cost));p.spent=this.time;const blade=this.weapon(),contact=blade.base.clone().lerp(blade.tip,.4);this.effects.impact(contact,'steel',heavy);this.audio.play(parry?'parry':'block');if(parry&&enemy){enemy.state='stagger';enemy.t=0;enemy.attack=null;enemy.lastBlade=null;enemy.cooldown=.6;}if(p.stamina===0){p.guard=false;p.stagger=.45;this.shieldBreakUntil=this.time+.75;}return;}
    const damage=raw||(heavy?29:18);p.health=Math.max(0,p.health-damage);p.stagger=.32;p.charge=null;p.attack=null;p.guard=false;this.effects.impact(point,'blood');this.audio.play('hit-flesh');this.onHit(damage);
  }
  private rangedAttack(e:Enemy,dt:number){const mage=e.kind==='mage';e.view.pose(mage?'charge':'draw',Math.min(e.t,mage?1.15:1.0));if(mage&&e.t>.25&&Math.random()<dt*16){const point=e.view.weaponPoints().tip;this.effects.impact(point,'steel');}const duration=mage?1.15:1.0;if(e.t>=duration){const origin=e.pos.clone().add(new THREE.Vector3(0,1.42,0));const target=this.player.pos.clone().add(new THREE.Vector3(0,1.2,0));const distance=target.distanceTo(origin);target.addScaledVector(this.player.velocity,Math.min(.35,distance/(mage?13:25))*.5);this.launch(origin,target.sub(origin).normalize().multiplyScalar(mage?13:25),e.id,mage);e.state='recover';e.t=0;e.cooldown=mage?1.35:1.15;e.view.play(mage?'cast':'release',.02);this.audio.play(mage?'fire-release':'bow-release',e.pos,.8);if(mage&&distance<3.2){this.effects.fire(origin.clone().add(new THREE.Vector3(0,-.3,0)),3.2);if(!this.physics.wallBetween(origin,this.player.pos.clone().add(new THREE.Vector3(0,1.2,0))))this.damagePlayer(e,null,this.player.pos.clone().add(new THREE.Vector3(0,1,0)),22);}}}
  private launch(pos:THREE.Vector3,velocity:THREE.Vector3,owner:string,fire:boolean){if(this.projectiles.length>=24)return;const mesh=new THREE.Group();const mat=new THREE.MeshBasicMaterial({color:fire?0xffa51f:0x807255});const shaft=new THREE.Mesh(new THREE.CylinderGeometry(fire?.035:.012,fire?.055:.012,fire?.8:.78,5),mat);shaft.rotation.x=Math.PI/2;mesh.add(shaft);const tip=new THREE.Mesh(new THREE.ConeGeometry(fire?.075:.038,.15,4),new THREE.MeshBasicMaterial({color:fire?0xffdf9a:0xc0bfb2}));tip.rotation.x=-Math.PI/2;tip.position.z=-.45;mesh.add(tip);mesh.position.copy(pos);mesh.lookAt(pos.clone().add(velocity));mesh.rotateY(Math.PI);this.scene.add(mesh);this.projectiles.push({mesh,pos:pos.clone(),velocity,life:5,owner,fire});}
  private updateProjectiles(dt:number){this.projectiles=this.projectiles.filter(b=>{b.life-=dt;const next=b.pos.clone().addScaledVector(b.velocity,dt);const hit=this.physics.raySurface(b.pos,next,b.owner);if(hit){if(hit.tag.kind==='player'){const enemy=this.enemies.get(b.owner)||null;this.damagePlayer(enemy,null,hit.point,b.fire?24:17);}this.effects.impact(hit.point,b.fire?'fire':hit.tag.kind==='player'?'blood':'stone',b.fire);this.audio.play(b.fire?'fire-impact':hit.tag.kind==='trunk'||hit.tag.kind==='wood'?'impact-wood':'impact-stone',hit.point,.8);b.life=0;}b.pos.copy(next);b.mesh.position.copy(next);if(!b.fire)b.velocity.y-=dt*2.8;if(b.life<=0){this.disposeProjectile(b);return false;}return true;});}
  private disposeProjectile(b:Projectile){b.mesh.removeFromParent();b.mesh.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();(o.material as THREE.Material).dispose();}});}
  private remember(e:Enemy,clock:number){this.recent.delete(e.id);this.recent.set(e.id,{id:e.id,kind:e.kind,x:e.pos.x+this.origin.x,y:e.pos.y,z:e.pos.z+this.origin.z,homeX:e.home.x+this.origin.x,homeZ:e.home.z+this.origin.z,health:e.health,seen:clock,dead:e.state==='dead',event:e.event});while(this.recent.size>TUNE.recentLimit)this.recent.delete(this.recent.keys().next().value!);}
  capture(clock:number){for(const e of this.enemies.values())if(!e.royal)this.remember(e,clock);return [...this.recent.values()].filter(r=>r.kind!=='elite').slice(-TUNE.recentLimit);}
  private removeEnemy(id:string){const e=this.enemies.get(id);if(!e)return;if(e.body)this.physics.removeCapsule(e.body);e.view.dispose();e.view.root.removeFromParent();this.enemies.delete(id);}
  rebase(x:number,z:number){const dx=x-this.origin.x,dz=z-this.origin.z;for(const e of this.enemies.values()){e.pos.x-=dx;e.pos.z-=dz;e.home.x-=dx;e.home.z-=dz;e.view.root.position.copy(e.pos);if(e.lastBlade){for(const v of [e.lastBlade.base,e.lastBlade.tip]){v.x-=dx;v.z-=dz;}}}for(const b of this.projectiles){b.pos.x-=dx;b.pos.z-=dz;b.mesh.position.copy(b.pos);}if(this.lastPlayerBlade){for(const v of [this.lastPlayerBlade.base,this.lastPlayerBlade.tip]){v.x-=dx;v.z-=dz;}}this.origin={x,z};}
  clearTransient(){for(const b of this.projectiles)this.disposeProjectile(b);this.projectiles=[];this.lastPlayerBlade=null;this.player.attack=null;this.player.charge=null;this.player.guard=false;this.player.stagger=0;this.player.dodge=0;this.player.feint=0;this.effects.clear();this.audio.clear();for(const e of this.enemies.values()){if(e.state!=='dead'){e.state='idle';e.t=0;e.attack=null;e.lastBlade=null;e.cooldown=1.2;e.alert=false;}}}
  resetEnemies(){this.clearTransient();for(const e of [...this.enemies.values()])this.removeEnemy(e.id);this.syncAt=0;}
  dispose(){this.resetEnemies();}
}
