import * as THREE from 'three';
import type {Settings} from './state';
interface Fleck {p:THREE.Vector3;v:THREE.Vector3;life:number;max:number;color:THREE.Color;scale:number;blood:boolean;}
interface Burst {mesh:THREE.Mesh;life:number;max:number;size:number;}
export class Effects {
  root=new THREE.Group();private particles:Fleck[]=[];private sparks:THREE.InstancedMesh;private dummy=new THREE.Object3D();private pools:THREE.Mesh[]=[];private bursts:Burst[]=[];private trail:THREE.Mesh;private trailLife=0;
  constructor(private settings:Settings){const g=new THREE.PlaneGeometry(.035,.20);const m=new THREE.MeshBasicMaterial({color:0xffffff,side:THREE.DoubleSide,transparent:true,depthWrite:false,vertexColors:false});this.sparks=new THREE.InstancedMesh(g,m,384);this.sparks.instanceMatrix.setUsage(THREE.DynamicDrawUsage);this.sparks.count=0;this.sparks.frustumCulled=false;this.root.add(this.sparks);const tg=new THREE.BufferGeometry();tg.setAttribute('position',new THREE.BufferAttribute(new Float32Array(18),3));const tm=new THREE.MeshBasicMaterial({color:0xf2f0d9,side:THREE.DoubleSide,transparent:true,opacity:.18,depthWrite:false});this.trail=new THREE.Mesh(tg,tm);this.trail.frustumCulled=false;this.trail.visible=false;this.root.add(this.trail);}
  configure(s:Settings){this.settings=s;if(!s.blood){for(const p of this.pools){p.removeFromParent();p.geometry.dispose();(p.material as THREE.Material).dispose();}this.pools=[];this.particles=this.particles.filter(p=>!p.blood);}}
  impact(point:THREE.Vector3,kind:'steel'|'blood'|'stone'|'fire',strong=false){if(kind==='blood'&&!this.settings.blood)return;const n=kind==='fire'?42:kind==='steel'?20:14;for(let i=0;i<n&&this.particles.length<384;i++){const a=Math.random()*Math.PI*2,b=Math.random()*2-1;const v=new THREE.Vector3(Math.cos(a)*Math.sqrt(1-b*b),b,Math.sin(a)*Math.sqrt(1-b*b)).multiplyScalar(kind==='blood'?1.4:3+Math.random()*3);const life=kind==='fire'?.6+Math.random()*.5:.13+Math.random()*.24;this.particles.push({p:point.clone(),v,life,max:life,color:new THREE.Color(kind==='blood'?0x812b34:kind==='stone'?0xb1ada0:i%3?0xffd47a:0xfff0c3),scale:strong?1.5:1,blood:kind==='blood'});}if(kind==='fire')this.fire(point,strong?3.3:1.9);}
  fire(point:THREE.Vector3,size=2.5){if(this.bursts.length>=8)return;const mat=new THREE.ShaderMaterial({transparent:true,depthWrite:false,side:THREE.DoubleSide,uniforms:{time:{value:0},alpha:{value:this.settings.flashes?.85:.42}},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:`varying vec2 vUv;uniform float time,alpha;void main(){vec2 p=(vUv-.5)*2.;float r=length(p);float a=atan(p.y,p.x);float curl=sin(a*7.+r*15.-time*14.)*.065+sin(a*3.-time*9.)*.09;float ring=1.-smoothstep(.05,.25,abs(r-.55-curl));float inner=(1.-smoothstep(.0,.6,r))*.5;float fade=1.-time;vec3 color=mix(vec3(1.,.20,.005),vec3(1.,.83,.30),pow(ring,3.));gl_FragColor=vec4(color,(ring+inner)*fade*alpha);}`});const mesh=new THREE.Mesh(new THREE.PlaneGeometry(1,1),mat);mesh.position.copy(point);mesh.scale.set(size,size,1);this.root.add(mesh);this.bursts.push({mesh,life:.65,max:.65,size});const ground=new THREE.Mesh(new THREE.RingGeometry(.75,1,32),new THREE.MeshBasicMaterial({color:0xff6f12,transparent:true,opacity:.65,side:THREE.DoubleSide,depthWrite:false}));ground.position.copy(point).add(new THREE.Vector3(0,-.7,0));ground.rotation.x=-Math.PI/2;ground.scale.setScalar(size*.5);this.root.add(ground);this.bursts.push({mesh:ground,life:.5,max:.5,size:size*.5});}
  pool(point:THREE.Vector3){if(!this.settings.blood)return;const shape=new THREE.Shape();for(let i=0;i<18;i++){const a=i/18*Math.PI*2,r=.45+Math.random()*.26;const x=Math.cos(a)*r,y=Math.sin(a)*r*.65;if(i===0)shape.moveTo(x,y);else shape.lineTo(x,y);}shape.closePath();const mesh=new THREE.Mesh(new THREE.ShapeGeometry(shape),new THREE.MeshLambertMaterial({color:0x4c1723,transparent:true,opacity:.92,depthWrite:false,side:THREE.DoubleSide,polygonOffset:true,polygonOffsetFactor:-1}));mesh.rotation.x=-Math.PI/2;mesh.position.copy(point).add(new THREE.Vector3(0,.025,0));this.root.add(mesh);this.pools.push(mesh);while(this.pools.length>12){const old=this.pools.shift()!;old.removeFromParent();old.geometry.dispose();(old.material as THREE.Material).dispose();}}
  slash(prev:{base:THREE.Vector3,tip:THREE.Vector3},next:{base:THREE.Vector3,tip:THREE.Vector3}){const p=this.trail.geometry.getAttribute('position') as THREE.BufferAttribute;const points=[prev.base,prev.tip,next.tip,prev.base,next.tip,next.base];points.forEach((v,i)=>p.setXYZ(i,v.x,v.y,v.z));p.needsUpdate=true;this.trail.visible=true;this.trailLife=.065;}
  update(dt:number,camera:THREE.Camera){this.particles=this.particles.filter(p=>{p.life-=dt;if(p.life<=0)return false;p.v.y-=p.blood?dt*9:dt*4;p.p.addScaledVector(p.v,dt);return true;});this.particles.forEach((p,i)=>{this.dummy.position.copy(p.p);this.dummy.quaternion.copy(camera.quaternion);this.dummy.rotateZ(Math.atan2(p.v.y,p.v.x));this.dummy.scale.set(p.blood?2:p.scale,p.scale*(p.life/p.max+.25),1);this.dummy.updateMatrix();this.sparks.setMatrixAt(i,this.dummy.matrix);this.sparks.setColorAt(i,p.color);});this.sparks.count=this.particles.length;this.sparks.instanceMatrix.needsUpdate=true;if(this.sparks.instanceColor)this.sparks.instanceColor.needsUpdate=true;this.trailLife-=dt;if(this.trailLife<=0)this.trail.visible=false;this.bursts=this.bursts.filter(b=>{b.life-=dt;const u=1-b.life/b.max;if(b.mesh.material instanceof THREE.ShaderMaterial){b.mesh.quaternion.copy(camera.quaternion);b.mesh.material.uniforms.time.value=u;}else (b.mesh.material as THREE.MeshBasicMaterial).opacity=(1-u)*.5;b.mesh.scale.setScalar(b.size*(1+u*.65));if(b.life>0)return true;b.mesh.removeFromParent();b.mesh.geometry.dispose();(b.mesh.material as THREE.Material).dispose();return false;});}
  rebase(dx:number,dz:number){for(const p of this.particles){p.p.x-=dx;p.p.z-=dz;}for(const p of [...this.pools,...this.bursts.map(b=>b.mesh)]){p.position.x-=dx;p.position.z-=dz;}this.trail.visible=false;this.trailLife=0;}
  clear(){this.particles=[];this.sparks.count=0;for(const b of this.bursts){b.mesh.removeFromParent();b.mesh.geometry.dispose();(b.mesh.material as THREE.Material).dispose();}this.bursts=[];this.trail.visible=false;}
  dispose(){this.clear();this.root.removeFromParent();this.root.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();(o.material as THREE.Material).dispose();}});}
}
