import type {Sector,Settings} from './state';
export interface InputFrame {x:number;z:number;sprint:boolean;attackDown:boolean;attackUp:boolean;guardDown:boolean;guard:boolean;dodge:boolean;interact:boolean;sector:Sector;lookX:number;lookY:number;}
export class Input {
  active=false; mode:'mouse'|'keyboard'|'gamepad'='mouse';sector:Sector='high';padConnected=false; private held=new Set<string>();
  private attack=false;private defend=false;private attackDown=false;private attackUp=false;private guardDown=false;private dodge=false;private interact=false;private mx=0;private my=0;private gx=0;private gy=0;private gestureAt=0;private ignoreUntil=0;private padLast:boolean[]=[];private padX=0;private padZ=0;private padSprint=false;private disposers:(()=>void)[]=[];
  constructor(private canvas:HTMLCanvasElement,public settings:Settings,private onPause:()=>void,private notice:(s:string)=>void,private menuMove:(delta:number,confirm:boolean,back:boolean)=>void){
    this.listen(window,'keydown',(event:Event)=>{const e=event as KeyboardEvent;if(e.code==='Escape'){e.preventDefault();if(this.active)this.onPause();return;}if(!this.active)return;if(e.repeat)return;this.held.add(e.code);if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();const b=this.settings.bindings;if(e.code===b.high)this.sector='high';if(e.code===b.guardLeft)this.sector='left';if(e.code===b.guardRight)this.sector='right';if(e.code===b.low)this.sector='low';if(e.code===b.dodge)this.dodge=true;if(e.code===b.interact||e.code==='Enter')this.interact=true;if(e.code==='KeyJ'){this.attack=true;this.attackDown=true;this.mode='keyboard';}if(e.code==='KeyK'){this.defend=true;this.guardDown=true;this.mode='keyboard';}});
    this.listen(window,'keyup',(event:Event)=>{const e=event as KeyboardEvent;this.held.delete(e.code);if(e.code==='KeyJ'&&this.attack){this.attack=false;this.attackUp=true;}if(e.code==='KeyK')this.defend=false;});
    this.listen(canvas,'mousedown',(event:Event)=>{const e=event as MouseEvent;if(!this.active||performance.now()<this.ignoreUntil)return;e.preventDefault();this.mode='mouse';if(e.button===0){this.attack=true;this.attackDown=true;}if(e.button===2){this.defend=true;this.guardDown=true;}});
    this.listen(window,'mouseup',(event:Event)=>{const e=event as MouseEvent;if(e.button===0&&this.attack){this.attack=false;if(this.active)this.attackUp=true;}if(e.button===2)this.defend=false;});
    this.listen(canvas,'contextmenu',(e:Event)=>e.preventDefault());
    this.listen(window,'mousemove',(event:Event)=>{if(!this.active||this.mode==='gamepad')return;const e=event as MouseEvent;if(document.pointerLockElement!==canvas&&e.target!==canvas)return;this.mx+=e.movementX;this.my+=e.movementY;const now=performance.now();if(now-this.gestureAt>170){this.gx=0;this.gy=0;}this.gestureAt=now;this.gx+=e.movementX;this.gy+=e.movementY;const ax=Math.abs(this.gx),ay=Math.abs(this.gy);if(Math.max(ax,ay)>80&&Math.abs(ax-ay)>28){this.sector=ax>ay?(this.gx<0?'left':'right'):(this.gy<0?'high':'low');this.gx=0;this.gy=0;}});
    this.listen(document,'pointerlockchange',()=>{if(!document.pointerLockElement&&this.active&&this.mode==='mouse'&&performance.now()>this.ignoreUntil)this.onPause();});
    this.listen(document,'pointerlockerror',()=>{if(this.active)this.notice('Mouse capture is unavailable in this App host. Use arrow keys to look, J to strike, K to guard, or a controller.');});
    this.listen(window,'blur',()=>{this.clear();if(this.active)this.onPause();});
    this.listen(document,'visibilitychange',()=>{if(document.hidden){this.clear();if(this.active)this.onPause();}});
    this.listen(window,'gamepadconnected',()=>{this.padConnected=true;this.notice('Controller connected. Right stick looks; D-pad selects your guard.');});
    this.listen(window,'gamepaddisconnected',()=>{this.padConnected=false;this.clear();if(this.active)this.onPause();this.notice('Controller disconnected. Resume with keyboard and mouse or reconnect.');});
  }
  private listen(target:EventTarget,type:string,cb:EventListener){target.addEventListener(type,cb);this.disposers.push(()=>target.removeEventListener(type,cb));}
  enter(controller=false){this.clear();this.active=true;this.ignoreUntil=performance.now()+250;this.mode=controller?'gamepad':'mouse';this.canvas.focus({preventScroll:true});if(!controller){try{const result=this.canvas.requestPointerLock();if(result&&typeof result.catch==='function')result.catch(()=>{this.notice('This host did not grant mouse capture. Arrow keys look; J strikes; K defends. A controller also works.');});}catch{this.notice('Mouse capture is unavailable. Arrow keys look; J strikes; K defends.');}}}
  leave(){this.active=false;this.clear();if(document.pointerLockElement===this.canvas)document.exitPointerLock();}
  clear(){this.held.clear();this.attack=false;this.defend=false;this.attackDown=false;this.attackUp=false;this.guardDown=false;this.dodge=false;this.interact=false;this.mx=this.my=this.gx=this.gy=0;this.padX=this.padZ=0;this.padSprint=false;this.padLast=[];}
  poll(dt:number){const pad=Array.from(navigator.getGamepads?.()||[]).find(p=>p?.connected);if(!pad)return;this.padConnected=true;const btn=pad.buttons.map(b=>b.pressed||b.value>.45);const edge=(i:number)=>btn[i]&&!this.padLast[i];const dz=(v:number)=>Math.abs(v)<.16?0:Math.sign(v)*(Math.abs(v)-.16)/.84;
    if(!this.active){if(btn.some(Boolean))this.mode='gamepad';if(edge(12)||edge(14))this.menuMove(-1,false,false);if(edge(13)||edge(15))this.menuMove(1,false,false);if(edge(0))this.menuMove(0,true,false);if(edge(1))this.menuMove(0,false,true);}
    else {this.padX=dz(pad.axes[0]||0);this.padZ=dz(pad.axes[1]||0);if(Math.abs(this.padX)+Math.abs(this.padZ)+Math.abs(pad.axes[2]||0)+Math.abs(pad.axes[3]||0)>.1||btn.some(Boolean)){this.mode='gamepad';}
      this.mx+=dz(pad.axes[2]||0)*dt*620;this.my+=dz(pad.axes[3]||0)*dt*500;if(edge(7)){this.attack=true;this.attackDown=true;}if(!btn[7]&&this.padLast[7]){this.attack=false;this.attackUp=true;}if(edge(6))this.guardDown=true;this.defend=Boolean(btn[6]);if(edge(1))this.dodge=true;if(edge(0))this.interact=true;if(edge(9))this.onPause();if(edge(10))this.padSprint=!this.padSprint;
      if(btn[12])this.sector='high';if(btn[13])this.sector='low';if(btn[14])this.sector='left';if(btn[15])this.sector='right';}
    this.padLast=btn;
  }
  frame(dt:number):InputFrame {const b=this.settings.bindings;const x=(this.held.has(b.right)?1:0)-(this.held.has(b.left)?1:0)+this.padX;const z=(this.held.has(b.back)?1:0)-(this.held.has(b.forward)?1:0)+this.padZ;const l=Math.max(1,Math.hypot(x,z));const out={x:x/l,z:z/l,sprint:this.held.has(b.sprint)||this.held.has('ShiftRight')||this.padSprint,attackDown:this.attackDown,attackUp:this.attackUp,guardDown:this.guardDown,guard:this.defend,dodge:this.dodge,interact:this.interact,sector:this.sector,lookX:this.mx+((this.held.has('ArrowRight')?1:0)-(this.held.has('ArrowLeft')?1:0))*dt*590,lookY:this.my+((this.held.has('ArrowDown')?1:0)-(this.held.has('ArrowUp')?1:0))*dt*460};this.attackDown=this.attackUp=this.guardDown=this.dodge=this.interact=false;this.mx=this.my=0;return out;}
  dispose(){this.leave();for(const dispose of this.disposers)dispose();}
}
