import * as THREE from 'three';
import {App} from '@modelcontextprotocol/ext-apps';
import serif from '@fontsource/cormorant-garamond/files/cormorant-garamond-latin-400-normal.woff2?url';
import italic from '@fontsource/cormorant-garamond/files/cormorant-garamond-latin-400-italic.woff2?url';
import sans from '@fontsource/inter/files/inter-latin-400-normal.woff2?url';
import {World} from './world';
import {createTerrain} from './terrain';
import {loadCharacters,VIEWMODEL_MOUNT,type CharacterLibrary,type CharacterView} from './characters';
import {GameAudio} from './audio';
import {View} from './renderer';
import {Input} from './input';
import {Physics} from './physics';
import {Combat,type Player} from './combat';
import {Castle} from './castle';
import {Effects} from './effects';
import {UI,$} from './ui';
import {Saves,TUNE,settingsRead,freshSave,skyState,type SaveRecord} from './state';
const style=document.createElement('style');style.textContent=`@font-face{font-family:'Gloaming Serif';src:url('${serif}') format('woff2');font-weight:400;font-display:swap}@font-face{font-family:'Gloaming Serif';src:url('${italic}') format('woff2');font-style:italic;font-weight:400;font-display:swap}@font-face{font-family:'Gloaming Sans';src:url('${sans}') format('woff2');font-weight:400 600;font-display:swap}`;document.head.append(style);
const settings=settingsRead(),ui=new UI(settings),saves=new Saves(),audio=new GameAudio();const canvas=$<HTMLCanvasElement>('scene');
let view:View,library:CharacterLibrary,world:World,physics:Physics,castle:Castle,effects:Effects,combat:Combat,weapon:CharacterView,princess:CharacterView,player:Player,record:SaveRecord;let stored:SaveRecord|null=null;let loaded=false;let lastFrame=0,accumulator=0,autosave=0,foot=0,premise=0;let conversation:string[]=[],conversationIndex=0,rescuePending=false;let interaction:{kind:'door'|'princess'|'rest';id:string;x?:number;z?:number}|null=null;let hadStorage=false,disposed=false,loadingVersion=0,stepBlocked=false,lastAudioError='';
const app=new App({name:'The Gloaming Road',version:'1.0.0'},{availableDisplayModes:['inline','fullscreen']},{autoResize:false});
const input=new Input(canvas,settings,()=>pause('Your world waits exactly as you left it.'),s=>ui.toast(s),(d,c,b)=>ui.menu(d,c,b));
app.ontoolresult=()=>{};app.onhostcontextchanged=()=>view?.resize();app.onteardown=async()=>{await persist();dispose();return {};};if(window.parent!==window)void app.connect().catch(()=>ui.toast('App bridge is unavailable. The game and local saves still work.'));
function click(id:string,fn:()=>void){$(id).addEventListener('click',(e)=>{if(e.isTrusted&&(e as MouseEvent).detail>0)input.mode='mouse';fn();});}
async function unlock(){try{const ok=await audio.unlock();$('audio-unlock').hidden=ok;return ok;}catch{$('audio-unlock').hidden=false;return false;}}
function startGesture(){void unlock();input.enter(input.mode==='gamepad');lastFrame=performance.now();accumulator=0;}
ui.onSettings=()=>{audio.settings(settings);view?.configure(settings);world?.configureQuality(settings.quality);effects?.configure(settings);};
ui.onBack=()=>{if(ui.phase==='dialogue'){advanceConversation();return;}if(ui.panelName==='pause'){resume();return;}if(ui.phase==='paused')ui.panel('pause');else if(ui.phase==='dead')ui.panel('death');else ui.title(!!stored);};
document.querySelectorAll<HTMLButtonElement>('[data-open]').forEach(b=>b.onclick=()=>{if(ui.phase==='playing')pause();ui.panel(b.dataset.open!);audio.play('ui');});
click('start',()=>{void unlock();audio.cue('title');ui.panel('new');$('replace-warning').textContent=stored?'Beginning a new world replaces the saved journey in this browser. Your current seed and progress will be lost.':'Choose a seed, or leave the world to chance. Nothing here tells you which way to go.';});
click('create',()=>{const seed=$<HTMLInputElement>('seed').value.trim()||`gloaming-${crypto.getRandomValues(new Uint32Array(1))[0].toString(36)}`;const loading=newWorld(seed);startGesture();void loading.catch(error=>{input.leave();ui.fail(error);});});
click('continue',()=>{if(loaded&&record){startGesture();ui.setPhase('playing');audio.resume();view.resetTimings();}else if(stored){startGesture();void loadWorld(stored).then(()=>{ui.setPhase('playing');audio.resume();});}});
click('resume',resume);click('save-quit',()=>void quit());click('death-quit',()=>void quit());click('respawn',()=>{const loading=respawn();startGesture();void loading.catch(error=>{input.leave();ui.fail(error);});});click('retry',()=>location.reload());click('audio-unlock',()=>void unlock());click('dialogue-next',advanceConversation);
function resume(){if(!loaded)return;startGesture();ui.setPhase('playing');audio.resume();view.resetTimings();}
function pause(reason='Your world waits exactly as you left it.'){if(ui.phase!=='playing')return;input.leave();ui.setPhase('paused');$('pause-reason').textContent=reason;$('pause-seed').textContent=`World seed · ${record.seed}`;ui.panel('pause');audio.pause();accumulator=0;void persist();}
async function quit(){input.leave();await persist();combat?.clearTransient();ui.title(!!stored);audio.pause();audio.cue('title');lastFrame=0;}
function cloneRecord(){if(!record||!player)return null;record.player={x:player.pos.x+world.origin.x,y:player.pos.y,z:player.pos.z+world.origin.z,yaw:player.yaw,pitch:player.pitch,health:player.health,stamina:player.stamina};record.mission.doors=castle.doorState();record.recent=combat.capture(record.clock);record.savedAt=Date.now();return structuredClone(record);}
async function persist(){const data=cloneRecord();if(!data)return;try{await saves.write(data);stored=data;}catch(e){ui.toast(e instanceof Error?e.message:'Progress is not being saved: browser storage failed.');}}
async function newWorld(seed:string){const terrain=createTerrain(seed),next=freshSave(seed,terrain.features);await loadWorld(next);if(!loaded)return;await persist();ui.setPhase('playing');premise=9;$('premise').hidden=false;$('premise').style.opacity='1';audio.resume();view.resetTimings();}
async function loadWorld(save:SaveRecord){const version=++loadingVersion;ui.setPhase('loading');ui.load('Laying the ground beneath your feet',65);loaded=false;combat?.dispose();princess?.dispose();princess?.root.removeFromParent();weapon?.dispose();weapon?.root.removeFromParent();castle?.dispose();world?.dispose();effects?.dispose();physics?.dispose();record=structuredClone(save);physics=new Physics();world=new World(record.seed,{onLoad:data=>physics.addChunk(data),onUnload:key=>physics.removeChunk(key)},settings.quality);view.scene.add(world.root);castle=await Castle.load(record.features.castle,record.mission.doors);if(version!==loadingVersion)return;view.scene.add(castle.root);if(record.player.health<=0){record.player.x=record.recovery.x;record.player.z=record.recovery.z;record.player.y=world.terrain.height(record.recovery.x,record.recovery.z)+.08;record.player.health=100;record.player.stamina=100;}const x=record.player.x,z=record.player.z;const originX=Math.floor(x/TUNE.rebase)*TUNE.rebase,originZ=Math.floor(z/TUNE.rebase)*TUNE.rebase;world.setOrigin(originX,originZ);physics.rebase(originX,originZ);castle.setOrigin(originX,originZ);await world.prepare(x,z);if(version!==loadingVersion)return;physics.syncChunks(x,z);if(castle.near(x,z))castle.activate(physics);ui.load('Giving the world its voices',90);
  const y=record.player.y;player={body:physics.capsule(x-originX,y+.025,z-originZ,'player',true),pos:new THREE.Vector3(x-originX,y,z-originZ),yaw:record.player.yaw,pitch:record.player.pitch,health:record.player.health||100,stamina:record.player.stamina,sector:'high',guard:false,guardAt:0,spent:record.clock-2,stagger:0,charge:null,attack:null,dodge:0,dodgeX:0,dodgeZ:0,feint:0,velocity:new THREE.Vector3()};
  effects=new Effects(settings);view.scene.add(effects.root);weapon=library.create('viewmodel');view.viewScene.add(weapon.root);weapon.root.position.set(...VIEWMODEL_MOUNT.position);weapon.root.rotation.set(...VIEWMODEL_MOUNT.rotation);weapon.pose('idle',0);
  const pp=castle.princess();princess=library.create('princess');princess.root.position.set(pp.x-originX,pp.y,pp.z-originZ);princess.root.rotation.y=0;princess.play('idle');view.scene.add(princess.root);
  combat=new Combat(physics,library,view.scene,audio,effects,world.terrain,castle,record,player,()=>weaponPoints(),(name,t)=>weapon.pose(name,t),id=>{if(!record.mission.defeated.includes(id)){record.mission.defeated.push(id);void persist();}},()=>{ui.hit(!settings.flashes);});combat.rebase(originX,originZ);
  // Query acceleration structures must be populated before first controller step.
  physics.step();player.pos.copy(physics.feet(player.body));setCamera(0);input.clear();accumulator=0;lastFrame=0;autosave=0;foot=0;loaded=true;ui.load('The road is yours',100);
}
function weaponPoints(){weapon.root.updateWorldMatrix(true,true);const points=weapon.weaponPoints();view.camera.updateMatrixWorld();for(const p of [points.base,points.tip])p.applyMatrix4(view.camera.matrixWorld);return points;}
function setCamera(dt:number){const pos=player.pos;const movement=player.velocity.length();const bob=settings.motion?Math.sin(foot*Math.PI*2)*.012*Math.min(1,movement):0;view.camera.position.set(pos.x,pos.y+TUNE.eye+bob,pos.z);view.camera.rotation.order='YXZ';view.camera.rotation.set(player.pitch,player.yaw,0);view.camera.updateMatrixWorld();if(weapon){weapon.root.position.x=VIEWMODEL_MOUNT.position[0]+Math.sin(record.clock*1.6)*.003;weapon.root.position.y=VIEWMODEL_MOUNT.position[1]+(settings.motion?Math.sin(foot*Math.PI*2)*.010:0);weapon.root.rotation.z=settings.motion?Math.sin(foot*Math.PI)*.004:0;}}
function fixed(dt:number){const p=player;const frame=input.frame(dt);p.yaw-=frame.lookX*.0022*settings.sensitivity;p.pitch=THREE.MathUtils.clamp(p.pitch-frame.lookY*.0022*settings.sensitivity*(settings.invert?-1:1),-1.35,1.35);if(p.attack)p.yaw=THREE.MathUtils.clamp(p.yaw,p.attack.yaw-.42,p.attack.yaw+.42);
  combat.playerInput(frame,dt,record.clock);const move=frame.sprint&&p.stamina>2&&!p.attack&&!p.guard?TUNE.sprint:TUNE.walk;const weight=p.stagger>0?.25:p.attack?.62:p.guard?.68:1;const desiredX=(frame.x*Math.cos(p.yaw)+frame.z*Math.sin(p.yaw))*move*weight,desiredZ=(-frame.x*Math.sin(p.yaw)+frame.z*Math.cos(p.yaw))*move*weight;p.velocity.x=THREE.MathUtils.damp(p.velocity.x,desiredX,18,dt);p.velocity.z=THREE.MathUtils.damp(p.velocity.z,desiredZ,18,dt);if(p.dodge>0){p.velocity.x=p.dodgeX;p.velocity.z=p.dodgeZ;}const nx=p.pos.x+p.velocity.x*dt+world.origin.x,nz=p.pos.z+p.velocity.z*dt+world.origin.z;if(!world.readyAt(nx,nz)||!physics.ready(nx,nz)){stepBlocked=true;$('stream-wait').hidden=false;return;}stepBlocked=false;$('stream-wait').hidden=true;record.clock+=dt;
  if(frame.sprint&&Math.hypot(frame.x,frame.z)>.2&&move===TUNE.sprint){p.stamina=Math.max(0,p.stamina-dt*6);p.spent=record.clock;}physics.move(p.body,p.velocity.x*dt,p.velocity.z*dt,dt);const sky=skyState(record.clock,record.seed);combat.sync(world.encounters,record.clock,sky.blood?sky.day:undefined,(x,z)=>world.readyAt(x,z)&&physics.ready(x,z));combat.update(dt,record.clock);castle.updateDoors(dt);physics.step();const before=p.pos.clone();p.pos.copy(physics.feet(p.body));const walked=Math.hypot(p.pos.x-before.x,p.pos.z-before.z);foot+=walked/1.5;if(Math.floor(foot)!==Math.floor(foot-walked/1.5)&&p.body.grounded){const gx=p.pos.x+world.origin.x,gz=p.pos.z+world.origin.z;const surface=castle.inside(gx,p.pos.y,gz)||Math.hypot(gx-castle.feature.x,gz-castle.feature.z)<30?'stone':world.terrain.path(gx,gz)>.6?'dirt':'grass';audio.play(`step-${surface}`,undefined,frame.sprint?.60:.42);}
  if(Math.abs(p.pos.x)>TUNE.rebase||Math.abs(p.pos.z)>TUNE.rebase){const ox=world.origin.x,oz=world.origin.z;const x=ox+Math.floor(p.pos.x/TUNE.rebase)*TUNE.rebase,z=oz+Math.floor(p.pos.z/TUNE.rebase)*TUNE.rebase;const dx=x-ox,dz=z-oz;physics.rebase(x,z);p.pos.x-=dx;p.pos.z-=dz;world.setOrigin(x,z);castle.setOrigin(x,z);combat.rebase(x,z);effects.rebase(dx,dz);audio.rebase(dx,dz);princess.root.position.x-=dx;princess.root.position.z-=dz;accumulator=0;}
  setCamera(dt);effects.update(dt,view.camera);princess.update(dt);const gx=p.pos.x+world.origin.x,gz=p.pos.z+world.origin.z;const inside=castle.inside(gx,p.pos.y,gz);audio.listener(view.camera.position,view.camera.getWorldDirection(new THREE.Vector3()));audio.mix({biome:world.terrain.biome(gx,gz),night:sky.night,blood:sky.blood,inside,threat:combat.threat,royal:combat.royalThreat},dt);updateInteraction(gx,gz);if(frame.interact&&interaction)interact();ui.hud(p.health,p.stamina,p.sector,combat.threat,p.guard);
  if(premise>0){premise-=dt;if(premise<3)$('premise').style.opacity='0';if(premise<=0)$('premise').hidden=true;}autosave+=dt;if(autosave>25){autosave=0;void persist();}if(p.health<=0){input.leave();combat.clearTransient();ui.setPhase('dead');ui.panel('death');audio.pause();void persist();}
}
function updateInteraction(x:number,z:number){interaction=null;const point=castle.princess();const d=Math.hypot(point.x-x,point.z-z);if(d<2.3&&Math.abs(player.pos.y-point.y)<2&&castle.chamber(x,z)&&!physics.wallBetween(view.camera.position,new THREE.Vector3(point.x-world.origin.x,point.y+1.3,point.z-world.origin.z))){interaction={kind:'princess',id:'elowen'};}else{const door=castle.interaction(x,z,player.yaw);if(door)interaction={kind:'door',id:door.id};else{const rests=[...world.rests,{id:'first-clearing',x:record.features.spawn.x,z:record.features.spawn.z}];const r=rests.find(r=>Math.hypot(r.x-x,r.z-z)<2.3);if(r&&!combat.threat)interaction={kind:'rest',id:r.id,x:r.x,z:r.z};}}ui.prompt(interaction?interaction.kind==='door'?'Open':interaction.kind==='princess'?'Talk':'Rest':null,input.mode==='gamepad');}
function interact(){if(!interaction)return;const it=interaction;if(it.kind==='door'){castle.openDoor(it.id);audio.play('door',player.pos,.85);void persist();return;}if(it.kind==='rest'){record.recovery={id:it.id,x:it.x!,z:it.z!};player.health=100;player.stamina=100;audio.play('rest');ui.toast('You rest. This quiet place will remember you.');void persist();return;}const clear=record.mission.guardIds.every(id=>record.mission.defeated.includes(id));rescuePending=clear&&!record.mission.rescued;conversation=record.mission.rescued?["The door is open. I think I will stay a little, and watch the light.","Wherever the road takes you, go gently."]:clear?["For so long, there was only the wind beyond these walls.","You came. I'm safe now. Thank you."]:["They're still here. I can hear their armor in the hall."];conversationIndex=0;input.leave();ui.setPhase('dialogue');$('dialogue-line').textContent=conversation[0];$('dialogue-next').focus();princess.play('talk',.2);audio.pause();}
function advanceConversation(){if(ui.phase!=='dialogue')return;conversationIndex++;if(conversationIndex<conversation.length){$('dialogue-line').textContent=conversation[conversationIndex];princess.play('talk',.1);return;}if(rescuePending&&!record.mission.rescued&&record.mission.guardIds.every(id=>record.mission.defeated.includes(id))){record.mission.rescued=true;rescuePending=false;void persist();audio.cue('rescue');$('announce').textContent='Elowen is safe. The world remains open to you.';}princess.play('idle');resume();}
async function respawn(){ui.setPhase('loading');ui.load('Returning to a quiet place',70);combat.resetEnemies();player.health=100;player.stamina=100;const x=record.recovery.x,z=record.recovery.z;await world.prepare(x,z);physics.syncChunks(x,z);const y=world.terrain.height(x,z);physics.teleport(player.body,x-world.origin.x,y+.08,z-world.origin.z);physics.step();player.pos.copy(physics.feet(player.body));player.velocity.set(0,0,0);player.yaw=record.features.spawn.yaw;player.pitch=0;input.clear();setCamera(0);ui.setPhase('playing');audio.resume();audio.play('respawn');await persist();lastFrame=0;}
function frame(now:number){if(disposed)return;const audioStatus=audio.diagnostics;if(audioStatus.activated&&audioStatus.context==='running')$('audio-unlock').hidden=true;const audioError=String(audioStatus.lastError||'');if(audioError&&audioError!==lastAudioError){lastAudioError=audioError;ui.toast(audioError);}const dt=lastFrame?Math.min(.1,(now-lastFrame)/1000):0;lastFrame=now;input.poll(dt);if(loaded){const gx=player.pos.x+world.origin.x,gz=player.pos.z+world.origin.z;world.update(gx,gz,dt);physics.syncChunks(gx,gz);if(castle.near(gx,gz))castle.activate(physics);else if(!combat.royalThreat)castle.deactivate();if(ui.phase==='playing'){accumulator=Math.min(accumulator+dt,.1);let steps=0;while(accumulator>=TUNE.step&&steps++<5&&ui.phase==='playing'){fixed(TUNE.step);accumulator-=TUNE.step;}if(stepBlocked)accumulator=0;}else accumulator=0;view.atmosphere(record.clock,record.seed,world.terrain.biome(gx,gz),Math.max(dt,.016),world.origin.x,world.origin.z);world.illuminate(view.fill.color,Math.min(1,.42+view.sun.intensity*.32));if(ui.phase==='title'){princess.update(dt);weapon.pose('idle',record.clock%4);}view.render(ui.phase==='playing');}else if(view)view.render(false);}
function dispose(){if(disposed)return;disposed=true;combat?.dispose();castle?.dispose();world?.dispose();effects?.dispose();input.dispose();audio.dispose();view?.dispose();physics?.dispose();saves.close();}
window.addEventListener('pagehide',()=>{void persist();audio.pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){if(ui.phase==='playing')pause('Paused while you were away.');audio.pause();}else if(ui.phase==='title')audio.cue('title');});
async function boot(){try{ui.load('Lighting the sky',5);view=new View(canvas,settings);view.renderer.setAnimationLoop(frame);try{await saves.open();hadStorage=true;stored=await saves.read();}catch(e){ui.toast(e instanceof Error?e.message:'Progress cannot be saved in this browser.');}ui.load('Forging steel and setting the stones',12);await Physics.initialize();let progress=15;[library]=await Promise.all([loadCharacters(label=>ui.load(label,Math.min(48,progress+=4))),audio.load(label=>ui.load(label,Math.min(62,progress+=1)))]);audio.settings(settings);const initial=stored??freshSave('silver-thistle',createTerrain('silver-thistle').features);await loadWorld(initial);ui.title(!!stored);const small=matchMedia('(pointer:coarse) and (max-width:700px)').matches;$('unsupported').hidden=!small;if(small)window.addEventListener('gamepadconnected',()=>$('unsupported').hidden=true);audio.cue('title');}catch(error){console.error('The Gloaming Road could not start:',error);ui.fail(error);}}
void boot();
