import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import cloudURL from './assets/atmosphere/clouds.png?url';
import moonURL from './assets/atmosphere/moon.png?url';
import type {Settings} from './state';
import {skyState} from './state';
const lerp=THREE.MathUtils.lerp;
export class View {
  renderer:THREE.WebGLRenderer;scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(65,16/9,.045,2600);viewScene=new THREE.Scene();viewCamera=new THREE.PerspectiveCamera(65,16/9,.045,6);sun=new THREE.DirectionalLight(0xffedc5,1.8);fill=new THREE.HemisphereLight(0xabb4d6,0x263b23,1.5);target:THREE.WebGLRenderTarget;sky:THREE.Mesh;moon:THREE.Sprite;private post=new THREE.Scene();private postCamera=new THREE.OrthographicCamera(-1,1,1,-1,0,1);private output:THREE.ShaderMaterial;private skyMat:THREE.ShaderMaterial;private resizeObserver:ResizeObserver;private dragon=new THREE.Group();private wings:THREE.Mesh[]=[];private renderTimes:number[]=[];private last=0;private dragonCycle=-1;private dragonAnchor=new THREE.Vector3();
  constructor(public canvas:HTMLCanvasElement,private settings:Settings){
    this.renderer=new THREE.WebGLRenderer({canvas,antialias:false,alpha:false,powerPreference:'high-performance'});this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.NoToneMapping;this.renderer.shadowMap.enabled=settings.quality!=='low';this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.autoClear=false;this.renderer.info.autoReset=false;
    this.target=new THREE.WebGLRenderTarget(960,540,{type:THREE.UnsignedByteType,minFilter:THREE.NearestFilter,magFilter:THREE.NearestFilter,depthBuffer:true});
    this.scene.fog=new THREE.FogExp2(0xa29bc0,.0017);this.scene.add(this.fill,this.sun,this.sun.target);this.sun.castShadow=true;this.sun.shadow.mapSize.set(1024,1024);this.sun.shadow.camera.left=-35;this.sun.shadow.camera.right=35;this.sun.shadow.camera.top=35;this.sun.shadow.camera.bottom=-35;this.sun.shadow.camera.near=1;this.sun.shadow.camera.far=140;this.sun.shadow.bias=-.001;this.sun.shadow.normalBias=.06;
    const vmFill=new THREE.HemisphereLight(0xd6d9de,0x35402d,2.0),vmSun=new THREE.DirectionalLight(0xffe3bd,1.6);vmSun.position.set(-3,5,1);this.viewScene.add(vmFill,vmSun);this.viewScene.add(this.viewCamera);
    const clouds=new THREE.TextureLoader().load(cloudURL);clouds.wrapS=clouds.wrapT=THREE.RepeatWrapping;clouds.magFilter=THREE.LinearFilter;
    this.skyMat=new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,uniforms:{cloud:{value:clouds},time:{value:0},top:{value:new THREE.Color(0x6667bb)},horizon:{value:new THREE.Color(0xc0b1d3)},cloudLight:{value:new THREE.Color(0xb3accf)},dark:{value:0},blood:{value:0}},vertexShader:'varying vec3 vDir; void main(){vDir=position; gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:`uniform sampler2D cloud; uniform float time,dark,blood;uniform vec3 top,horizon,cloudLight;varying vec3 vDir;
      void main(){vec3 d=normalize(vDir);float up=clamp(d.y,0.,1.);vec2 sphereUv=vec2(atan(d.z,d.x)/6.283185+.5,asin(d.y)/3.141593+.5);vec2 uv=sphereUv*vec2(2.,4.);float n=texture2D(cloud,uv+vec2(time*.000016,0.)).r;float detail=texture2D(cloud,uv*vec2(3.,2.)-vec2(time*.000011,0.)).r;float wisps=texture2D(cloud,uv*vec2(9.,6.)).r;float field=n*.74+detail*.2+wisps*.06;float c=smoothstep(.45,.57,field)*smoothstep(-.06,.15,d.y);vec3 color=mix(horizon,top,pow(up,.42));vec3 lit=mix(cloudLight*.65,cloudLight,smoothstep(.44,.66,field));color=mix(color,lit,c*.94);float stars=step(.992,fract(sin(dot(floor(sphereUv*vec2(2200.,900.)),vec2(12.9898,78.233)))*43758.5453));color+=stars*dark*up*.55*(1.-c);gl_FragColor=vec4(color,1.);}`});
    this.sky=new THREE.Mesh(new THREE.SphereGeometry(2300,32,18),this.skyMat);this.sky.renderOrder=-20;this.sky.frustumCulled=false;this.scene.add(this.sky);
    const moonTexture=new THREE.TextureLoader().load(moonURL);moonTexture.colorSpace=THREE.SRGBColorSpace;moonTexture.magFilter=THREE.NearestFilter;this.moon=new THREE.Sprite(new THREE.SpriteMaterial({map:moonTexture,color:0xffffff,transparent:true,depthWrite:false,fog:false}));this.moon.scale.set(170,170,1);this.moon.renderOrder=-10;this.scene.add(this.moon);
    this.output=new THREE.ShaderMaterial({depthTest:false,depthWrite:false,uniforms:{image:{value:this.target.texture}},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=vec4(position.xy,0.,1.);}',fragmentShader:`uniform sampler2D image;varying vec2 vUv;
      vec3 srgb(vec3 v){return mix(v*12.92,1.055*pow(max(v,vec3(0.)),vec3(1./2.4))-.055,step(vec3(.0031308),v));}
      void main(){vec3 c=srgb(texture2D(image,vUv).rgb);vec2 p=mod(gl_FragCoord.xy,4.);float b=mod(p.x*2.+p.y*3.,4.);float d=(b/3.-.5)/125.;c=floor(clamp(c+d,0.,1.)*127.+.5)/127.;gl_FragColor=vec4(c,1.);}`});this.post.add(new THREE.Mesh(new THREE.PlaneGeometry(2,2),this.output));
    this.buildDragon();this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(canvas.parentElement!);this.resize();
  }
  resize(){const w=Math.max(1,this.canvas.parentElement!.clientWidth),h=Math.max(1,this.canvas.parentElement!.clientHeight);const target=this.settings.quality==='low'?360:this.settings.quality==='high'?720:540;const scale=this.settings.quality==='high'?Math.max(1,h/target):Math.max(1,Math.ceil(h/target));const rw=Math.round(w/scale),rh=Math.round(h/scale);this.renderer.setSize(rw,rh,false);this.target.setSize(rw,rh);this.camera.aspect=rw/rh;this.camera.fov=this.settings.fov;this.camera.updateProjectionMatrix();this.viewCamera.aspect=rw/rh;this.viewCamera.fov=this.settings.fov;this.viewCamera.updateProjectionMatrix();this.renderer.shadowMap.enabled=this.settings.quality!=='low';}
  configure(settings:Settings){this.settings=settings;this.resize();}
  atmosphere(clock:number,seed:string,biome:string,dt:number,originX=0,originZ=0){const s=skyState(clock,seed);const night=THREE.MathUtils.smoothstep(-s.sun,-.12,.25);const dusk=Math.max(0,1-Math.abs(s.sun)/.32)*(s.t>.3?1:0);const blood=s.blood?night:0;const forest=biome==='woodland'||biome==='conifer';const c=(day:number,n:number,red:number)=>new THREE.Color(day).lerp(new THREE.Color(n),night).lerp(new THREE.Color(red),blood);const top=c(0x7066b7,0x182038,0x541829).lerp(new THREE.Color(0xa678a1),dusk*.5);const horizon=c(0xb6accb,0x515e73,0x78343f).lerp(new THREE.Color(0xd8a38e),dusk*.65);const cloud=c(0xd2bde0,0x384659,0x8d3c4d);this.skyMat.uniforms.top.value.lerp(top,.035);this.skyMat.uniforms.horizon.value.lerp(horizon,.035);this.skyMat.uniforms.cloudLight.value.lerp(cloud,.035);this.skyMat.uniforms.dark.value=night;this.skyMat.uniforms.blood.value=blood;this.skyMat.uniforms.time.value=clock;
    const fog=this.scene.fog as THREE.FogExp2;const fogColor=forest?c(0x9da9ab,0x4a5b66,0x623b49):horizon;fog.color.lerp(fogColor,Math.min(1,dt*1.6));fog.density=lerp(fog.density,forest?.010:night?.003:.0017,Math.min(1,dt*.8));this.fill.color.copy(c(forest?0xabc6c7:0xbdbdd9,0x7c91b5,0xb66c7b));this.fill.groundColor.copy(c(0x3a492e,0x26322c,0x422132));this.fill.intensity=lerp(1.45,.85,night)*(forest?.88:1);this.sun.intensity=lerp(forest?1.05:1.85,.27,night);this.sun.color.copy(c(0xffe4b5,0xa9bdd9,0xe59276).lerp(new THREE.Color(0xffb77f),dusk*.8));
    const p=this.camera.position;this.sky.position.copy(p);this.sun.position.copy(p).add(new THREE.Vector3(-38,65,24));this.sun.target.position.copy(p);const moonPos=new THREE.Vector3(680,500,-1100);this.moon.position.copy(p).add(moonPos);this.moon.material.color.set(s.blood?0xf46757:0xeee4c9);this.moon.material.opacity=night;const size=s.blood?390:140;this.moon.scale.set(size,size,1);const cycle=Math.floor(clock/270),flight=clock%270;if(cycle!==this.dragonCycle){this.dragonCycle=cycle;this.dragonAnchor.set(Math.round((p.x+originX)/512)*512,p.y+145,Math.round((p.z+originZ)/512)*512-620);}this.dragon.position.set(this.dragonAnchor.x+(flight/70-.5)*1500-originX,this.dragonAnchor.y+Math.sin(clock*.025)*18,this.dragonAnchor.z-originZ);this.dragon.visible=flight<70&&!s.night&&this.dragon.position.distanceTo(p)<1900;for(let i=0;i<this.wings.length;i++)this.wings[i].rotation.z=(i?1:-1)*(.2+Math.sin(clock*1.8)*.34);
  }
  private buildDragon(){const mat=new THREE.MeshBasicMaterial({color:0x252c3a,fog:true,side:THREE.DoubleSide});const body=new THREE.Mesh(new THREE.ConeGeometry(.9,7,5),mat);body.rotation.x=Math.PI/2;this.dragon.add(body);const head=new THREE.Mesh(new THREE.ConeGeometry(.55,3,5),mat);head.position.set(0,.4,-4.3);head.rotation.x=-Math.PI/2;this.dragon.add(head);for(const sign of [-1,1]){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute([0,0,0,sign*5,1,-4,sign*14,.4,-2,0,0,0,sign*14,.4,-2,sign*10,.1,1,0,0,0,sign*10,.1,1,sign*7,-.2,.5,0,0,0,sign*7,-.2,.5,sign*4,0,3,0,0,0,sign*4,0,3,0,0,2],3));const wing=new THREE.Mesh(g,mat);this.dragon.add(wing);this.wings.push(wing);}const tail=new THREE.Mesh(new THREE.ConeGeometry(.42,8,4),mat);tail.rotation.x=Math.PI/2;tail.position.z=5.8;this.dragon.add(tail);this.dragon.rotation.y=-Math.PI/2;this.scene.add(this.dragon);}
  render(showWeapon:boolean){const now=performance.now();if(this.last){this.renderTimes.push(now-this.last);if(this.renderTimes.length>600)this.renderTimes.shift();}this.last=now;this.renderer.info.reset();this.renderer.setRenderTarget(this.target);this.renderer.clear();this.renderer.render(this.scene,this.camera);if(showWeapon){this.renderer.clearDepth();this.viewCamera.quaternion.identity();this.viewCamera.position.set(0,0,0);this.renderer.render(this.viewScene,this.viewCamera);}this.renderer.setRenderTarget(null);this.renderer.clear();this.renderer.render(this.post,this.postCamera);}
  diagnostics(){const a=this.renderTimes.slice().sort((a,b)=>a-b);return {width:this.canvas.width,height:this.canvas.height,drawCalls:this.renderer.info.render.calls,triangles:this.renderer.info.render.triangles,geometries:this.renderer.info.memory.geometries,textures:this.renderer.info.memory.textures,frameP50:a[Math.floor(a.length*.5)]||0,frameP95:a[Math.floor(a.length*.95)]||0,renderer:this.renderer.getContext().getParameter(this.renderer.getContext().RENDERER)};}
  resetTimings(){this.renderTimes=[];this.last=0;}
  dispose(){this.resizeObserver.disconnect();this.renderer.setAnimationLoop(null);this.renderer.dispose();this.target.dispose();}
}
