import {defaults,settingsWrite,type Settings} from './state';
export const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
export class UI {
  phase='loading';panelName='';returnPanel='';private toastTimer=0;private captionTimer=0;private waitingBind:string|null=null;onSettings:()=>void=()=>{};onBack:()=>void=()=>{};
  constructor(public settings:Settings){this.buildSettings();document.querySelectorAll<HTMLButtonElement>('[data-back]').forEach(b=>b.onclick=()=>this.onBack());document.addEventListener('keydown',e=>{if(this.waitingBind){e.preventDefault();if(e.code!=='Escape'){this.settings.bindings[this.waitingBind]=e.code;this.persist();}this.waitingBind=null;this.buildBindings();return;}if(this.phase==='playing'||this.phase==='loading')return;if(e.code==='ArrowDown'||e.code==='ArrowUp'){e.preventDefault();this.menu(e.code==='ArrowDown'?1:-1,false,false);}if(e.code==='Escape'&&this.panelName){e.preventDefault();if(this.panelName!=='pause'&&this.panelName!=='death'&&this.panelName!=='error')this.onBack();}if(e.code==='Tab'){const elements=this.focusables();if(!elements.length)return;if(e.shiftKey&&document.activeElement===elements[0]){e.preventDefault();elements.at(-1)!.focus();}else if(!e.shiftKey&&document.activeElement===elements.at(-1)){e.preventDefault();elements[0].focus();}}});}
  load(label:string,percent:number){$('loading').hidden=false;$('load-label').textContent=label;$('load-progress').style.width=`${percent}%`;}
  setPhase(phase:string){this.phase=phase;if(phase!=='playing')this.clearCaption();$('sound-caption').hidden=phase!=='playing'||!this.settings.captions;document.body.dataset.phase=phase;$('loading').hidden=phase!=='loading';$('title').hidden=phase!=='title';$('hud').hidden=phase!=='playing';$('dialogue').hidden=phase!=='dialogue';if(['playing','title','loading','dialogue'].includes(phase)){this.panelName='';$('panels').hidden=true;document.querySelectorAll<HTMLElement>('#panels>.panel').forEach(p=>p.hidden=true);}}
  panel(name:string){this.panelName=name;$('panels').hidden=false;document.querySelectorAll<HTMLElement>('#panels>.panel').forEach(p=>p.hidden=p.id!==name+'-panel');requestAnimationFrame(()=>this.focusables()[0]?.focus());}
  private focusables(){const parent=$('dialogue').hidden?this.panelName?$(this.panelName+'-panel'):$('title'):$('dialogue');return Array.from(parent.querySelectorAll<HTMLElement>('button:not(:disabled),input,select,a[href]')).filter(e=>e.offsetParent!==null);}
  menu(delta:number,confirm:boolean,back:boolean){if(back){this.onBack();return;}const els=this.focusables();if(!els.length)return;let i=els.indexOf(document.activeElement as HTMLElement);if(delta){i=(i+delta+els.length)%els.length;els[i].focus();}if(confirm){if(i<0)i=0;els[i].click();}}
  title(hasSave:boolean){this.setPhase('title');$('continue').hidden=!hasSave;$('start').className=hasSave?'text-button':'primary';$('start').querySelector('span')!.textContent=hasSave?'New world':'Enter the world';$('start').querySelector('.arrow')!.setAttribute('style',hasSave?'display:none':'');}
  toast(message:string){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(this.toastTimer);this.toastTimer=window.setTimeout(()=>$('toast').hidden=true,6500);$('announce').textContent=message;}
  /** Optional sound descriptions only; mandatory written dialogue is independent. */
  caption(text:string){
    if(this.phase!=='playing'||!this.settings.captions){this.clearCaption();return;}
    const message=text.replace(/\s+/g,' ').trim().slice(0,140);
    if(!message){this.clearCaption();return;}
    const region=$('sound-caption');region.hidden=false;
    if(region.textContent!==message)region.textContent=message;
    clearTimeout(this.captionTimer);this.captionTimer=window.setTimeout(()=>this.clearCaption(),2800);
  }
  private clearCaption(){clearTimeout(this.captionTimer);this.captionTimer=0;const region=$('sound-caption');region.textContent='';region.hidden=this.phase!=='playing'||!this.settings.captions;}
  fail(error:unknown){this.setPhase('error');$('error-text').textContent=error instanceof Error?error.message:String(error);this.panel('error');}
  hud(health:number,stamina:number,sector:string,combat:boolean,guard:boolean){$('health').style.width=`${Math.max(0,health)}%`;$('stamina').style.width=`${Math.max(0,stamina)}%`;$('health-meter').setAttribute('aria-valuenow',String(Math.round(health)));$('stamina-meter').setAttribute('aria-valuenow',String(Math.round(stamina)));$('resources').style.opacity=combat||health<100||stamina<98?'1':'.15';$('resource-label').textContent=stamina<12?'Guard exhausted':health<25?'Wounded':'Resolve';$('guard').hidden=!combat&&!guard;$('guard').dataset.sector=sector;$('guard').classList.toggle('defending',guard);$('guard').setAttribute('aria-label',`${guard?'Defending':'Selected guard'}: ${sector}`);}
  prompt(label:string|null,controller=false){$('prompt').hidden=!label;if(label){$('prompt').querySelector('kbd')!.textContent=controller?'A':'E';$('prompt').querySelector('span')!.textContent=label;}}
  hit(reduced=false){$('hit-wash').style.opacity=reduced?'.22':'1';window.setTimeout(()=>$('hit-wash').style.opacity='0',130);}
  private persist(){if(!this.settings.captions)this.clearCaption();try{settingsWrite(this.settings);}catch{this.toast('Settings could not be stored in this browser.');}this.onSettings();}
  private buildSettings(){const host=$('settings-fields');const range=(key:keyof Settings,label:string,min:number,max:number,step:number)=>{const line=document.createElement('label');line.className='setting';line.textContent=label;const wrap=document.createElement('span'),input=document.createElement('input'),out=document.createElement('output');input.type='range';input.min=String(min);input.max=String(max);input.step=String(step);input.value=String(this.settings[key]);input.setAttribute('aria-label',label);out.value=key==='fov'?`${this.settings[key]}°`:String(Math.round(Number(this.settings[key])*(max===1?100:100))/100);input.oninput=()=>{(this.settings as unknown as Record<string,unknown>)[key]=Number(input.value);out.value=key==='fov'?`${input.value}°`:max===1?`${Math.round(Number(input.value)*100)}`:input.value;this.persist();};wrap.append(input,out);line.append(wrap);host.append(line);};
    for(const [key,label] of [['master','Master volume'],['music','Music'],['ambience','Ambience'],['effects','Sound effects']] as const)range(key,label,0,1,.05);range('sensitivity','Mouse sensitivity',.3,2.5,.1);range('fov','Field of view',55,85,1);
    const checks:[keyof Settings,string,boolean][]=[['invert','Invert look Y',false],['motion','Reduced camera motion',true],['flashes','Reduced flashes',true],['blood','Blood effects',false],['captions','Sound captions',false]];for(const [key,label,inverse] of checks){const line=document.createElement('label');line.className='setting';line.textContent=label;const input=document.createElement('input');input.type='checkbox';input.checked=inverse?!this.settings[key]:!!this.settings[key];if(key==='captions')input.setAttribute('aria-describedby','sound-captions-help');input.onchange=()=>{(this.settings as unknown as Record<string,unknown>)[key]=inverse?!input.checked:input.checked;this.persist();};line.append(input);host.append(line);}
    const line=document.createElement('label');line.className='setting';line.textContent='Image detail';const select=document.createElement('select');for(const [v,t] of [['low','Soft · 360 lines'],['balanced','Original · 540 lines'],['high','Fine · 720 lines']]){const option=document.createElement('option');option.value=v;option.textContent=t;select.append(option);}select.value=this.settings.quality;select.onchange=()=>{this.settings.quality=select.value as Settings['quality'];this.persist();};line.append(select);host.append(line);this.buildBindings();}
  private buildBindings(){const host=$('bindings');host.replaceChildren();const names:Record<string,string>={forward:'Move forward',back:'Move backward',left:'Strafe left',right:'Strafe right',sprint:'Sprint',dodge:'Dodge',interact:'Interact',high:'High guard',guardLeft:'Left guard',guardRight:'Right guard',low:'Low guard'};for(const [action,code] of Object.entries(this.settings.bindings)){const row=document.createElement('div');row.className='setting';row.append(document.createTextNode(names[action]||action));const b=document.createElement('button');b.className='bind';b.textContent=code.replace('Key','').replace('Digit','');b.onclick=()=>{this.waitingBind=action;b.textContent='Press a key…';};row.append(b);host.append(row);}}
}
